import { requireValidLicense } from "../../../../../lib/license.ts";
import { CAPABILITIES, hashPassword, normalizeUsername, requireCapability, sessionFromRequest, validSameOrigin } from "../../../../../lib/auth.ts";
import { getDatabase } from "../../../../../lib/sqlite.ts";

const safe=(user:Record<string,unknown>)=>({id:String(user.id),username:String(user.username),name:String(user.name??user.username),isActive:user.isActive===true,permissions:user.owner===true?[...CAPABILITIES]:(Array.isArray(user.permissions)?user.permissions:[]).filter(value=>CAPABILITIES.includes(value as typeof CAPABILITIES[number])),owner:user.owner===true,createdAt:user.createdAt,updatedAt:user.updatedAt});
async function targetId(context:{params:Promise<{id:string}>}){return decodeURIComponent((await context.params).id)}
export async function PUT(request:Request,context:{params:Promise<{id:string}>}){const licenseDenied=await requireValidLicense();if(licenseDenied)return licenseDenied;const denied=await requireCapability(request,"settings.users.manage");if(denied)return denied;if(!validSameOrigin(request))return Response.json({error:"طلب غير صالح"},{status:403});try{const db=await getDatabase(),id=await targetId(context),user=await db.collection("users").findOne({id});if(!user)return Response.json({error:"المستخدم غير موجود"},{status:404});const body=await request.json(),isOwner=user.owner===true,isActive=body.isActive!==false;if(user.isActive===true&&!isActive&&await db.collection("users").countDocuments({isActive:true})<=1)return Response.json({error:"لا يمكن تعطيل المستخدم الوحيد. فعّل مستخدمًا آخر أولًا."},{status:409});const username=isOwner?String(user.username):String(body.username??user.username).trim(),usernameNormalized=normalizeUsername(username);if(!usernameNormalized)return Response.json({error:"اسم المستخدم مطلوب"},{status:400});const duplicate=await db.collection("users").findOne({usernameNormalized});if(duplicate&&duplicate.id!==id)return Response.json({error:"اسم المستخدم مستخدم بالفعل"},{status:409});const update:Record<string,unknown>={username,usernameNormalized,name:isOwner?user.name:String(body.name??username).trim()||username,isActive,updatedAt:new Date(),permissions:isOwner?user.permissions:(Array.isArray(body.permissions)?[...new Set(body.permissions.filter((value:unknown)=>typeof value==="string"&&CAPABILITIES.includes(value as typeof CAPABILITIES[number])))]:[])};if(String(body.password??""))update.passwordHash=hashPassword(String(body.password));await db.collection("users").updateOne({id},{$set:update});return Response.json({user:safe({...user,...update})})}catch(error){return Response.json({error:error instanceof Error?error.message:"بيانات المستخدم غير صالحة"},{status:400})}}
export const PATCH=PUT;
export async function DELETE(request:Request,context:{params:Promise<{id:string}>}){const licenseDenied=await requireValidLicense();if(licenseDenied)return licenseDenied;const denied=await requireCapability(request,"settings.users.manage");if(denied)return denied;if(!validSameOrigin(request))return Response.json({error:"طلب غير صالح"},{status:403});const db=await getDatabase(),id=await targetId(context),user=await db.collection("users").findOne({id});if(!user)return Response.json({error:"المستخدم غير موجود"},{status:404});if(user.isActive===true&&await db.collection("users").countDocuments({isActive:true})<=1)return Response.json({error:"لا يمكن حذف المستخدم الوحيد. أنشئ أو فعّل مستخدمًا آخر أولًا."},{status:409});await db.collection("users").deleteOne({id});const session=sessionFromRequest(request),logoutRequired=(session?.principalType==="owner"&&id==="owner")||(session?.principalType==="user"&&session.userId===id);return Response.json({deleted:true,id,logoutRequired})}
