import test from "node:test";
import assert from "node:assert/strict";
import initSqlJs from "sql.js";
import { BACKUP_COLLECTIONS, BACKUP_SCHEMA_VERSION, parseAndValidateBackup, stringifyBackup } from "../lib/backup.ts";
import { detectLegacyDatabase, inspectLegacyDatabase, resolveSqlJsWasmPath } from "../legacy/dataacc-sqlite.ts";
import { readApiResponse } from "../app/api-response.ts";
import { appendLegacyChunk, finishLegacyUpload, LEGACY_CHUNK_BYTES, removeLegacyUpload, startLegacyUpload } from "../legacy/upload-store.ts";
import { readFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import { basename, isAbsolute } from "node:path";

function backup() {
  const collections=Object.fromEntries(BACKUP_COLLECTIONS.map(name=>[name,[]]));
  collections.warehouses=[{_id:"wh",name:"Main",isSalesDefault:true,createdAt:new Date("2024-01-02T03:04:05Z")}];
  collections.paymentAccounts=[{id:"account-cash",code:"cash",name:"Cash"}];
  collections.products=[{id:"p1",sku:"0001",barcode:"123",stocks:{wh:2},createdAt:new Date("2024-01-02T03:04:05Z")}];
  collections.documents=[{id:"d1",number:"SAL-1",kind:"sale",warehouseId:"wh",paymentMethod:"cash",lines:[{productId:"p1"}]}];
  return {format:"conta-backup",schemaVersion:1,createdAt:new Date().toISOString(),appVersion:"test",encoding:"mongodb-extended-json-v2",collections,counts:Object.fromEntries(BACKUP_COLLECTIONS.map(k=>[k,collections[k].length]))};
}
test("native backup is versioned, complete, secret-free, and preserves BSON dates",()=>{const value=backup(),encoded=stringifyBackup(value);assert.equal(value.schemaVersion,BACKUP_SCHEMA_VERSION);for(const name of BACKUP_COLLECTIONS)assert.ok(name in value.collections);for(const secret of ["MONGODB_URI","SESSION_SECRET","OWNER_PASSWORD_HASH"])assert.equal(encoded.includes(secret),false);const decoded=parseAndValidateBackup(encoded);assert.ok(decoded.collections.products[0].createdAt instanceof Date);});
test("native backup rejects invalid formats, future schemas, duplicate ids and references",()=>{assert.throws(()=>parseAndValidateBackup("{}"),/ليس نسخة/);const future=backup();future.schemaVersion=2;assert.throws(()=>parseAndValidateBackup(stringifyBackup(future)),/أحدث/);const duplicate=backup();duplicate.collections.products.push({...duplicate.collections.products[0]});assert.throws(()=>parseAndValidateBackup(stringifyBackup(duplicate)),/معرف المنتج/);const broken=backup();broken.collections.documents[0].lines[0].productId="missing";assert.throws(()=>parseAndValidateBackup(stringifyBackup(broken)),/منتج غير موجود/);});
test("SQLite detection uses magic and schema preview reads real counts",async()=>{assert.equal(detectLegacyDatabase(new TextEncoder().encode("not sqlite")),false);const SQL=await initSqlJs();const db=new SQL.Database();db.run("CREATE TABLE itemsTB(id INTEGER, title TEXT, code TEXT); INSERT INTO itemsTB VALUES (1,'A','123'),(2,'B','456'); CREATE TABLE storesTB(id INTEGER,title TEXT); INSERT INTO storesTB VALUES(1,'Main'); CREATE TABLE userTB(id INTEGER,password TEXT); INSERT INTO userTB VALUES(1,'secret');");const bytes=db.export();db.close();assert.equal(detectLegacyDatabase(bytes),true);const preview=await inspectLegacyDatabase(bytes);assert.equal(preview.groups.find(x=>x.key==='products').count,2);assert.equal(preview.groups.find(x=>x.key==='warehouses').count,1);assert.equal(preview.groups.find(x=>x.key==='userTB').status,'unsupported');});
test("sql.js runtime resolves the real WASM file without import.meta.resolve",async()=>{const wasmPath=resolveSqlJsWasmPath();assert.equal(isAbsolute(wasmPath),true);assert.equal(existsSync(wasmPath),true);assert.equal(basename(wasmPath),"sql-wasm.wasm");const runtime=await readFile(new URL("../legacy/dataacc-sqlite.ts",import.meta.url),"utf8");assert.equal(runtime.includes("import.meta.resolve"),false);});
test("API response reader turns an HTML 413 into a safe Arabic error",async()=>{await assert.rejects(readApiResponse(new Response("<html><h1>413</h1></html>",{status:413,headers:{"content-type":"text/html"}})),/حجم الملف تجاوز الحد المسموح به في خادم الويب/);});
test("6MB SQLite is accepted and reassembled in ordered safe chunks",async()=>{const SQL=await initSqlJs(),db=new SQL.Database();db.run("CREATE TABLE itemsTB(id INTEGER, title TEXT); INSERT INTO itemsTB VALUES(1,'large');");const exported=db.export();db.close();const bytes=new Uint8Array(6*1024*1024+17);bytes.set(exported);const started=await startLegacyUpload(bytes.length);try{for(let i=0,offset=0;offset<bytes.length;i++,offset+=LEGACY_CHUNK_BYTES)await appendLegacyChunk(started.uploadId,i,bytes.slice(offset,offset+LEGACY_CHUNK_BYTES));const complete=await finishLegacyUpload(started.uploadId);assert.equal(complete.length,bytes.length);assert.equal((await inspectLegacyDatabase(complete)).groups.find(x=>x.key==="products").count,1);}finally{await removeLegacyUpload(started.uploadId);}});
test("chunk upload rejects missing, duplicate and invalid SQLite data",async()=>{const missing=await startLegacyUpload(LEGACY_CHUNK_BYTES+1);try{await assert.rejects(appendLegacyChunk(missing.uploadId,1,new Uint8Array(1)),/ترتيب/);await appendLegacyChunk(missing.uploadId,0,new Uint8Array(LEGACY_CHUNK_BYTES));await assert.rejects(appendLegacyChunk(missing.uploadId,0,new Uint8Array(LEGACY_CHUNK_BYTES)),/ترتيب/);await assert.rejects(finishLegacyUpload(missing.uploadId),/غير مكتملة/);}finally{await removeLegacyUpload(missing.uploadId);}const invalid=await startLegacyUpload(16);try{await appendLegacyChunk(invalid.uploadId,0,new Uint8Array(16));await assert.rejects(finishLegacyUpload(invalid.uploadId),/ليس قاعدة/);}finally{await removeLegacyUpload(invalid.uploadId);}});
test("standalone configuration traces the sql.js WASM runtime",async()=>{const config=await readFile(new URL("../next.config.ts",import.meta.url),"utf8");assert.match(config,/sql-wasm\.wasm/);assert.match(config,/outputFileTracingIncludes/);});
test("chunk upload rejects totals above the 50MB application limit",async()=>{await assert.rejects(startLegacyUpload(50*1024*1024+1),/أكبر من الحد/);});
