import assert from "node:assert/strict";
import test from "node:test";
import { readFile, access } from "node:fs/promises";
const source=await readFile(new URL("../app/conta-app.tsx",import.meta.url),"utf8"),hover=await readFile(new URL("../app/hover-enter.ts",import.meta.url),"utf8"),css=await readFile(new URL("../app/globals.css",import.meta.url),"utf8");
test("custom invoice shortcut and help layer is completely removed",async()=>{await assert.rejects(access(new URL("../app/invoice-keyboard.ts",import.meta.url)));for(const stale of ["KeyboardHelp","invoiceKeyboardShortcuts","keyboard-help","Ctrl+Enter","F1","F2","F4"])assert.equal(source.includes(stale)||css.includes(stale),false)});
test("searchable select retains native keyboard accessibility",()=>{assert.match(source,/role="combobox"[\s\S]{0,250}aria-activedescendant/);assert.match(source,/e\.key === "ArrowDown"/);assert.match(source,/e\.key === "Enter" && highlightedIndex !== null/);assert.match(source,/e\.key === "Escape"[\s\S]{0,100}closeSelect\(true\)/)});
test("shared hover Enter helper is explicit, scoped, and prevents doubles",()=>{assert.match(source,/useHoverEnterActivation\(\)/);assert.match(hover,/\[data-hover-enter="select"\]/);assert.doesNotMatch(hover,/elementFromPoint/);assert.match(hover,/hovered === document\.activeElement \|\| hovered\.contains\(document\.activeElement\)/);assert.match(hover,/isTypingTarget\(event.target\)/);for(const target of ["input", "textarea", "select", "contenteditable"])assert.match(hover,new RegExp(target));assert.match(hover,/aria-modal/)});
test("sale and purchase product choices use existing add callback once",()=>{assert.match(source,/<tr id=\{`product-result-\$\{product\.id\}`\} data-hover-enter="select"/);assert.match(source,/data-hover-enter="select" role="option"[\s\S]{0,500}onClick=\{\(\) => add\(product\)\}/);assert.doesNotMatch(source,/onDoubleClick=\{\(\) => add\(product\)\}/)});
test("danger and submit actions never opt in",()=>{for(const label of ["حذف الفاتورة","إتمام البيع","إتمام الشراء"]) {const at=source.indexOf(label);assert.ok(at>0);assert.doesNotMatch(source.slice(Math.max(0,at-300),at),/data-hover-enter/)}});
