import test from "node:test";
import assert from "node:assert/strict";
import {mkdtemp,readFile,rm,stat,writeFile} from "node:fs/promises";
import {tmpdir} from "node:os";
import {join} from "node:path";
import {webcrypto} from "node:crypto";
import {canonicalLicensePayload,canonicalLicensePayloadV2,formatDeviceCode,getLicensePath,installLicense,MAX_LICENSE_BYTES,parseLicenseFile,readInstalledLicense,resetLicenseRuntimeState,verifyLicenseFile,getLicenseStatus} from "../lib/license.ts";
import {PUBLIC_LICENSE_KEYS} from "../lib/license-public-key.ts";

const device="AKD-1111-2222-3333-4444-5555";
const payload={licenseId:"fixture-001",storeId:"store-001",customerName:"عميل اختبار",storeName:"محل اختبار",deviceId:device,edition:"desktop",type:"perpetual",issuedAt:"2026-08-31T00:00:00.000Z",notes:""};
async function fixture(overrides={}){const pair=await webcrypto.subtle.generateKey({name:"ECDSA",namedCurve:"P-256"},true,["sign","verify"]),publicKey=await webcrypto.subtle.exportKey("jwk",pair.publicKey),value={...payload,...overrides},signature=Buffer.from(await webcrypto.subtle.sign({name:"ECDSA",hash:"SHA-256"},pair.privateKey,new TextEncoder().encode(canonicalLicensePayload(value)))).toString("base64url");return {text:JSON.stringify({schema:"alkarna-license",version:1,keyId:"test-key",algorithm:"ECDSA_P256_SHA256",payload:value,signature}),keys:{"test-key":publicKey},pair}}
function productionShape(text){return text.replace('"test-key"','"alkarna-license-v1"')}

test("device identity is private, deterministic and human friendly",()=>{const a=formatDeviceCode("{AABBCCDD-0011}"),b=formatDeviceCode("aabbccdd-0011");assert.equal(a,b);assert.match(a,/^AKD-(?:[A-F0-9]{4}-){4}[A-F0-9]{4}$/);assert.ok(!a.includes("AABBCCDD"))});
test("production public key is the exact verify-only P-256 contract",()=>{assert.deepEqual(PUBLIC_LICENSE_KEYS["alkarna-license-v1"],{kty:"EC",crv:"P-256",x:"VafWOl9h-bF8auIQTUvS5AATeR8yyxJu49p-QSzk7-s",y:"Pz7QrSsgtgcKhvc_eSblH0BPcBwEo9lCo-0zkXwIDzM",ext:true,key_ops:["verify"]});assert.equal("d" in PUBLIC_LICENSE_KEYS["alkarna-license-v1"],false)});
test("canonical payload preserves generator field order",()=>assert.equal(canonicalLicensePayload(payload),'{"licenseId":"fixture-001","storeId":"store-001","customerName":"عميل اختبار","storeName":"محل اختبار","deviceId":"AKD-1111-2222-3333-4444-5555","edition":"desktop","type":"perpetual","issuedAt":"2026-08-31T00:00:00.000Z","notes":""}'));
test("WebCrypto accepts a valid canonical signature and rejects mutation",async()=>{const f=await fixture();const doc=await verifyLicenseFile(productionShape(f.text),device,{"alkarna-license-v1":f.keys["test-key"]});assert.equal(doc.payload.customerName,payload.customerName);const changed=productionShape(f.text).replace("عميل اختبار","عميل معدل");await assert.rejects(()=>verifyLicenseFile(changed,device,{"alkarna-license-v1":f.keys["test-key"]}),/توقيع/)});
test("valid signature for another device gets the dedicated Arabic error",async()=>{const f=await fixture({deviceId:"AKD-AAAA-BBBB-CCCC-DDDD-EEEE"});await assert.rejects(()=>verifyLicenseFile(productionShape(f.text),device,{"alkarna-license-v1":f.keys["test-key"]}),/هذا الترخيص مخصص لجهاز آخر/)});
test("strict envelope and signature validation rejects invalid contracts",async()=>{const f=await fixture();const base=JSON.parse(productionShape(f.text));for(const mutation of [{schema:"other"},{version:3},{algorithm:"other"},{keyId:"unknown"}])await assert.rejects(()=>verifyLicenseFile(JSON.stringify({...base,...mutation}),device,{"alkarna-license-v1":f.keys["test-key"]}),/غير مدعوم/);for(const signature of ["","%%%","abc",null,42])await assert.rejects(()=>verifyLicenseFile(JSON.stringify({...base,signature}),device,{"alkarna-license-v1":f.keys["test-key"]}),/توقيع/)});
test("malformed verification key details never leak WebCrypto errors",async()=>{const f=await fixture();await assert.rejects(()=>verifyLicenseFile(productionShape(f.text),device,{"alkarna-license-v1":{kty:"EC",crv:"P-256",x:"bad",y:"bad",key_ops:["verify"]}}),error=>error.message==="تعذر التحقق من توقيع الترخيص")});
test("malformed and oversized JSON is rejected before processing",()=>{assert.throws(()=>parseLicenseFile("{"),/غير مدعوم/);assert.throws(()=>parseLicenseFile("x".repeat(MAX_LICENSE_BYTES+1)),/أكبر من الحد/)});
test("atomic install persists under userData config and survives database replacement",async()=>{const root=await mkdtemp(join(tmpdir(),"alkarna-license-")),priorEnv={...process.env};try{process.env.NODE_ENV="test";process.env.ALKARNA_TEST_DEVICE_ID=device;process.env.ALKARNA_USER_DATA=root;const f=await fixture();const production=productionShape(f.text),keys={"alkarna-license-v1":f.keys["test-key"]};await installLicense(production,device,keys);const path=getLicensePath();assert.equal(path,join(root,"config","license.alkarna-license"));await writeFile(join(root,"data-copy.sqlite"),"replacement business database");const installed=await readInstalledLicense();assert.equal(installed,production);assert.ok((await stat(path)).isFile());assert.equal((await verifyLicenseFile(installed,device,keys)).payload.licenseId,payload.licenseId)}finally{process.env=priorEnv;await rm(root,{recursive:true,force:true})}});
test("business routes enforce licensing while activation and health routes remain exempt",async()=>{const business=["bootstrap","command","reports","settings/backup","settings/restore","settings/branding"];for(const route of business)assert.match(await readFile(new URL(`../app/api/${route}/route.ts`,import.meta.url),"utf8"),/requireValidLicense/);for(const route of ["license/device","license/status","license/install","health"])assert.doesNotMatch(await readFile(new URL(`../app/api/${route}/route.ts`,import.meta.url),"utf8"),/requireValidLicense/)});
test("application source contains no private EC JWK material",async()=>{for(const file of ["../lib/license-public-key.ts","../lib/license.ts"])assert.doesNotMatch(await readFile(new URL(file,import.meta.url),"utf8"),/(?:^|[,{]\s*)["']?d["']?\s*:/m)});

const v2base={licenseId:"AKL2-TEST",storeId:"store-v2",customerName:"عميل مؤقت",storeName:"متجر مؤقت",deviceId:device,edition:"desktop",type:"temporary",durationSeconds:3600,activationMode:"single-install",notes:""};
async function v2fixture(overrides={}){const pair=await webcrypto.subtle.generateKey({name:"ECDSA",namedCurve:"P-256"},true,["sign","verify"]),publicKey=await webcrypto.subtle.exportKey("jwk",pair.publicKey),value={...v2base,...overrides},signature=Buffer.from(await webcrypto.subtle.sign({name:"ECDSA",hash:"SHA-256"},pair.privateKey,new TextEncoder().encode(canonicalLicensePayloadV2(value)))).toString("base64url");return{text:JSON.stringify({schema:"alkarna-license",version:2,keyId:"alkarna-license-v2",algorithm:"ECDSA_P256_SHA256",payload:value,signature}),keys:{"alkarna-license-v2":publicKey}}}
async function v2env(run){const root=await mkdtemp(join(tmpdir(),"alkarna-v2-")),old={...process.env};try{process.env.NODE_ENV="test";process.env.ALKARNA_TEST_DEVICE_ID=device;process.env.ALKARNA_USER_DATA=join(root,"userdata");process.env.ALKARNA_LICENSE_STATE_PATH=join(root,"durable","state-v2.json");process.env.ALKARNA_LICENSE_DISABLE_REGISTRY="1";resetLicenseRuntimeState();await run(root)}finally{process.env=old;resetLicenseRuntimeState();await rm(root,{recursive:true,force:true})}}
const fakeClock=(wall=1_000_000)=>{let w=wall,m=0n;return{clock:{wallNow:()=>w,monotonicNow:()=>m},wall(ms){w+=ms},mono(ms){m+=BigInt(ms)*1_000_000n},setWall(value){w=value}}};
test("v2 public key and exact duration canonical contract are verify-only",()=>{assert.deepEqual(PUBLIC_LICENSE_KEYS["alkarna-license-v2"],{kty:"EC",crv:"P-256",x:"-kAStxv0yNuJ9GyzSNaiywfrZ5BziSWL5kJVMFOnRUY",y:"AburlAjGDOBSzFeNa2sxyd4XgLM5CWKuDR4Hpe57GYU",ext:true,key_ops:["verify"]});assert.equal(canonicalLicensePayloadV2(v2base),'{"licenseId":"AKL2-TEST","storeId":"store-v2","customerName":"عميل مؤقت","storeName":"متجر مؤقت","deviceId":"AKD-1111-2222-3333-4444-5555","edition":"desktop","type":"temporary","durationSeconds":3600,"activationMode":"single-install","notes":""}');assert.doesNotMatch(canonicalLicensePayloadV2(v2base),/expiresAt|notBefore|issuedAt/)});
test("v2 validates duration and perpetual contracts",async()=>v2env(async()=>{let f=await v2fixture();assert.equal((await verifyLicenseFile(f.text,device,f.keys)).version,2);f=await v2fixture({type:"perpetual",durationSeconds:null});assert.equal((await verifyLicenseFile(f.text,device,f.keys)).payload.type,"perpetual");for(const durationSeconds of [null,0,-1,1.5,"60"]){f=await v2fixture({durationSeconds});await assert.rejects(()=>verifyLicenseFile(f.text,device,f.keys),/غير صالح/)}f=await v2fixture({expiresAt:"2099-01-01T00:00:00Z"});await assert.rejects(()=>verifyLicenseFile(f.text,device,f.keys),/غير صالح/) }));
test("one-hour allowance uses monotonic runtime then closed wall time",async()=>v2env(async()=>{const f=await v2fixture(),time=fakeClock();await installLicense(f.text,device,f.keys,time.clock);let status=await getLicenseStatus(time.clock,device,f.keys);assert.equal(status.license.remainingSeconds,3600);time.wall(600000);time.mono(600000);status=await getLicenseStatus(time.clock,device,f.keys);assert.equal(status.license.remainingSeconds,3000);resetLicenseRuntimeState();time.wall(1200000);status=await getLicenseStatus(time.clock,device,f.keys);assert.equal(status.license.remainingSeconds,1800)}));
test("running session uses maximum, not sum, of monotonic and forward wall elapsed",async()=>v2env(async()=>{const f=await v2fixture({durationSeconds:10800}),time=fakeClock();await installLicense(f.text,device,f.keys,time.clock);time.mono(600000);time.wall(7200000);const status=await getLicenseStatus(time.clock,device,f.keys);assert.equal(status.license.remainingSeconds,3600)}));
test("clock rollback locks without restarting countdown",async()=>v2env(async()=>{const f=await v2fixture(),time=fakeClock(10*3600000);await installLicense(f.text,device,f.keys,time.clock);resetLicenseRuntimeState();time.setWall(9*3600000);const status=await getLicenseStatus(time.clock,device,f.keys);assert.equal(status.valid,false);assert.equal(status.code,"LICENSE_CLOCK_ROLLBACK");time.setWall(10*3600000);resetLicenseRuntimeState();assert.equal((await getLicenseStatus(time.clock,device,f.keys)).code,"LICENSE_CLOCK_ROLLBACK")}));
test("five-hour forward jump expires three-hour license and backward cannot revive it",async()=>v2env(async()=>{const f=await v2fixture({durationSeconds:10800}),time=fakeClock(10*3600000);await installLicense(f.text,device,f.keys,time.clock);time.wall(5*3600000);assert.equal((await getLicenseStatus(time.clock,device,f.keys)).code,"LICENSE_EXPIRED");time.setWall(10*3600000);resetLicenseRuntimeState();assert.equal((await getLicenseStatus(time.clock,device,f.keys)).code,"LICENSE_EXPIRED")}));
test("single-install receipt survives deletion of normal userData",async()=>v2env(async root=>{const f=await v2fixture({licenseId:"TEST-ONE"}),time=fakeClock();await installLicense(f.text,device,f.keys,time.clock);await rm(process.env.ALKARNA_USER_DATA,{recursive:true,force:true});resetLicenseRuntimeState();await assert.rejects(()=>installLicense(f.text,device,f.keys,time.clock),e=>e.code==="LICENSE_ALREADY_USED");assert.ok(await stat(join(root,"durable","state-v2.json")));assert.doesNotMatch(await readFile(join(root,"durable","state-v2.json"),"utf8"),/remainingMs/)}));
