import assert from "node:assert/strict";
import test from "node:test";
import { readFile } from "node:fs/promises";
import { resolvePartyType } from "../app/domain.ts";

test("legacy party roles resolve centrally without changing valid roles",()=>{const parties=[{id:"a"},{id:"b",partyType:"supplier"},{id:"c",partyType:"customer"}];assert.deepEqual(parties.map(resolvePartyType),["supplier","supplier","customer"]);assert.deepEqual(parties.filter(p=>resolvePartyType(p)==="customer").map(p=>p.id),["c"]);assert.deepEqual(parties.filter(p=>resolvePartyType(p)==="supplier").map(p=>p.id),["a","b"]);});

test("POS and party workspaces retain compact role-safe structure and empty rows",async()=>{const source=await readFile(new URL("../app/conta-app.tsx",import.meta.url),"utf8"),css=await readFile(new URL("../app/globals.css",import.meta.url),"utf8");assert.match(source,/className=\{`pos-payment-row\$\{payment === "note" \? " note" : ""\}`\}/);assert.match(source,/payment !== "note" && <ShortcutHintAnchor[\s\S]{0,180}<CompactPaymentSelector/);assert.doesNotMatch(source,/اختر عميلاً حقيقياً للبيع بالدين|ستسجل الفاتورة كاملة دينًا علينا للمورد/);assert.match(source,/resolvePartyType\(p\) === "customer"/);assert.match(source,/variant="pos-customer" ariaLabel="العميل"/);assert.match(source,/<PaymentAccountSelect accounts=\{suppliedAccounts\} activeOnly/);assert.doesNotMatch(source,/searchable=\{false\}|variant="pos-native"/);assert.match(source,/<bdi dir="ltr">\{party\.phone\|\|"—"\}<\/bdi>/);assert.match(source,/لا يوجد عملاء حتى الآن/);assert.match(source,/لا يوجد موردون/);assert.match(css,/\.pos-payment-row \{[^}]*display: grid[^}]*grid-template-columns: 50px 72px minmax\(0, 1fr\)[^}]*min-width: 0/s);assert.match(css,/\.payment-section \.compact-payment \{[^}]*grid-template-columns: 66px minmax\(150px, 1fr\)/s);assert.match(css,/\.pos-workspace \{ grid-template-columns: minmax\(0, 24fr\) minmax\(0, 41fr\) minmax\(0, 35fr\)/);assert.match(css,/\.section-parties, \.section-customers, \.section-suppliers/);});

test("comprehensive report reuses the four-card report footer without internal detail",async()=>{const source=await readFile(new URL("../app/conta-app.tsx",import.meta.url),"utf8"),css=await readFile(new URL("../app/globals.css",import.meta.url),"utf8");const overview=source.slice(source.indexOf('if(type==="overview")'),source.indexOf('  return <section className="reports-workspace"',source.indexOf('if(type==="overview")')));assert.doesNotMatch(overview,/إجمالي الداخل إلى الخزنة|إجمالي الخارج من الخزنة|رصيد الخزنة/);assert.match(overview,/className="report-summary-area overview-summary-area"/);assert.equal((overview.match(/className="report-kpi"/g)??[]).length,4);for(const key of ["currentAccountsBalance","currentInventoryValue","currentReceivable","currentPayable"])assert.match(overview,new RegExp(`result\\.summary\\.${key}`));assert.doesNotMatch(overview,/overview-debt-summary|overview-current-total|comprehensive-bank-disclosure|bank-detail/);assert.match(css,/\.comprehensive-report \.overview-summary-area \{[^}]*grid-column: 1 \/ -1/s);assert.match(css,/\.report-kpis\{[^}]*grid-template-columns:repeat\(4,minmax\(0,1fr\)\)/s);});

test("all visual row-order headers use the full Arabic serial label",async()=>{const source=await readFile(new URL("../app/conta-app.tsx",import.meta.url),"utf8");assert.doesNotMatch(source,/<th(?:\s+className="serial")?>م<\/th>/);assert.match(source,/className="account-session"/);assert.doesNotMatch(source,/className="owner-mark">م<\/span>/);});
