import test from "node:test";import assert from "node:assert/strict";import {readFileSync} from "node:fs";import {bankScopeMetrics,filterFinancialMovements,filterTransfers} from "../app/bank-filters.ts";
const movements=[{id:"1",paymentMethod:"a",type:"sale",occurredAt:"2026-08-10",amount:10},{id:"2",paymentMethod:"b",type:"expense",occurredAt:"2026-07-10",amount:4},{id:"3",paymentMethod:"a",type:"expense",occurredAt:"2026-08-12",amount:3}];
test("all-time and committed period scopes remain independent of account/type changes",()=>{assert.equal(filterFinancialMovements(movements,null).length,3);const period={from:"2026-08-01",to:"2026-08-31"};assert.equal(filterFinancialMovements(movements,period).length,2);assert.equal(filterFinancialMovements(movements,period,"a").length,2);assert.equal(filterFinancialMovements(movements,period,"a","sale").length,1);assert.equal(filterFinancialMovements(movements,null,"a","sale").length,1)});
test("bank summary uses active balances, external cash movements, and net party debts",()=>{const accounts=[{id:"a",code:"a",balance:90,isActive:true},{id:"b",code:"b",balance:40,isActive:false}],rows=[{direction:"in",amount:100,type:"sale"},{direction:"out",amount:20,type:"expense"},{direction:"in",amount:50,type:"transfer-in"}];assert.deepEqual(bankScopeMetrics(accounts,rows,[{receivable:25,payable:5},{receivable:0,payable:10}]),{currentBalance:90,income:100,expenses:20,owedToUs:20,weOwe:10})});
test("transfer filters preserve committed period and both account directions",()=>{const rows=[{occurredAt:"2026-08-10",fromAccountId:"a",toAccountId:"b"},{occurredAt:"2026-08-11",fromAccountId:"b",toAccountId:"a"},{occurredAt:"2026-07-01",fromAccountId:"a",toAccountId:"b"}];assert.equal(filterTransfers(rows,{from:"2026-08-01",to:"2026-08-31"},"a","b").length,1)});
test("adjustment history and financial detail overlay remain explicit and mounted",()=>{const source=readFileSync(new URL("../app/conta-app.tsx",import.meta.url),"utf8");assert.match(source,/manual-deposit.*manual-withdrawal/);assert.match(source,/FinancialOperationDetail/);assert.match(source,/detail&&<FinancialOperationDetail/);assert.match(source,/createPortal\(<div className="modal-overlay"/) });
test("bank sections are parent navigation state rather than content tabs",()=>{const source=readFileSync(new URL("../app/conta-app.tsx",import.meta.url),"utf8"),banks=source.slice(source.indexOf("function Banks"),source.indexOf("function PaymentAccountDialog"));assert.match(source,/const bankNav/);assert.match(source,/setBankTab\(item\.id\);navigate\("banks"\)/);assert.doesNotMatch(banks,/className="bank-tabs"/)});
test("bank transfer and adjustment workspaces use explicit split regions and logical form rows",()=>{const source=readFileSync(new URL("../app/conta-app.tsx",import.meta.url),"utf8"),css=readFileSync(new URL("../app/globals.css",import.meta.url),"utf8"),banks=source.slice(source.indexOf("function Banks"),source.indexOf("function PaymentAccountDialog"));assert.match(banks,/bank-panel-centered-legend/);assert.match(banks,/transfer-account-row/);assert.match(banks,/transfer-detail-row/);assert.match(banks,/adjustment-account-row/);assert.match(banks,/adjustment-detail-row/);assert.match(banks,/bank-history-date-row/);assert.match(banks,/bank-history-select-row/);assert.match(css,/\.bank-tab-transfers,\.bank-tab-adjustment\{[^}]*grid-template-columns:minmax\(0,1fr\) minmax\(0,1fr\)[^}]*grid-template-areas:"operation history"/);assert.match(css,/\.bank-tab-transfers>\.bank-operation,\.bank-tab-adjustment>\.bank-operation\{grid-area:operation\}/);assert.match(css,/\.bank-tab-transfers>\.bank-history,\.bank-tab-adjustment>\.bank-history\{grid-area:history\}/);assert.match(css,/\.bank-panel-centered-legend>legend\{[^}]*margin-inline:auto/);assert.doesNotMatch(css,/\.erp-fieldset>legend\{[^}]*margin-inline:auto/)});
test("bank record amount tones are scoped to amount cells and derive from direction",()=>{const source=readFileSync(new URL("../app/conta-app.tsx",import.meta.url),"utf8"),css=readFileSync(new URL("../app/globals.css",import.meta.url),"utf8"),banks=source.slice(source.indexOf("function Banks"),source.indexOf("function PaymentAccountDialog"));assert.match(banks,/m\.direction==="in"\?"bank-amount-positive":"bank-amount-negative"/);assert.match(banks,/className="num-cell bank-amount-neutral"/);assert.match(css,/\.bank-amount-positive\{color:#15803d/);assert.match(css,/\.bank-amount-negative\{color:#b91c1c/);assert.match(css,/\.bank-amount-neutral\{color:var\(--ink\)/);assert.doesNotMatch(css,/(?:tr|tbody)\.(?:bank-amount-positive|bank-amount-negative)/)});
