import assert from 'node:assert/strict';import test,{after,before,beforeEach} from 'node:test';import {sqliteHarness} from './sqlite-harness.mjs';
let harness,db;before(async()=>{harness=await sqliteHarness();db=harness.db});beforeEach(()=>harness.reset());after(()=>harness.close());
test('nested update operators, upsert and bulkWrite conform',async()=>{const c=db.collection('importRuns');await c.updateOne({id:'run'},{$set:{'counts.products':1,'stocks.wh-main':2},$inc:{'counts.products':2},$max:{'counts.products':5},$setOnInsert:{created:true}},{upsert:true});let row=await c.findOne({id:'run'});assert.deepEqual(row.counts,{products:5});assert.equal(row.stocks['wh-main'],2);await c.updateOne({id:'run'},{$unset:{'counts.products':1}});assert.deepEqual((await c.findOne({id:'run'})).counts,{});await c.bulkWrite([{updateOne:{filter:{id:'run'},update:{$inc:{value:1}}}}]);assert.equal((await c.findOne({id:'run'})).value,1)});
test('transactions serialize and release after rollback',async()=>{const c=db.collection('counters');await Promise.all(Array.from({length:20},(_,i)=>db.transaction(async()=>{const row=await c.findOne({_id:'shared'});await Promise.resolve();await c.updateOne({_id:'shared'},{$set:{value:Number(row?.value??0)+1},$setOnInsert:{}},{upsert:true});if(i===7)throw new Error('expected')})).map(p=>p.catch(e=>e)));assert.equal((await c.findOne({_id:'shared'})).value,19);await db.transaction(()=>c.updateOne({_id:'after'},{$set:{value:1}},{upsert:true}));assert.equal((await c.findOne({_id:'after'})).value,1)});
test('schema unique indexes reject persisted duplicate invariants',async()=>{await db.collection('products').insertOne({id:'a',sku:'100'});await assert.rejects(db.collection('products').insertOne({id:'b',sku:'100'}),error=>error.code===11000&&error.sqliteCode==='SQLITE_CONSTRAINT_UNIQUE');const indexes=db.native.prepare("SELECT name FROM sqlite_master WHERE type='index' AND name LIKE '%unique%'").all().map(x=>x.name);assert.ok(indexes.includes('documents_number_unique'));assert.ok(indexes.includes('users_username_normalized_unique'));assert.ok(indexes.includes('financial_document_type_active_unique'));assert.ok(!indexes.includes('financial_document_type_unique'))});
test('performance indexes support report candidate scans without changing query results',async()=>{const documents=db.collection('documents');await documents.insertMany([{id:'sale-a',kind:'sale',status:'posted',occurredAt:'2026-09-18T10:00:00.000Z',partyId:'p1',lines:[{productId:'prod-a'}]},{id:'sale-old',kind:'sale',status:'posted',occurredAt:'2026-08-01T10:00:00.000Z',partyId:'p1',lines:[{productId:'prod-b'}]},{id:'purchase-a',kind:'purchase',status:'posted',occurredAt:'2026-09-18T11:00:00.000Z',partyId:'p2',lines:[{productId:'prod-a'}]},{id:null,kind:'sale',status:'posted',occurredAt:'2026-09-18T12:00:00.000Z',partyName:'Null id',lines:[]}]);const ranged={kind:'sale',status:'posted',occurredAt:{$gte:'2026-09-01T00:00:00.000Z',$lt:'2026-10-01T00:00:00.000Z'}};assert.deepEqual((await documents.find(ranged).toArray()).map(row=>row.partyId??row.partyName),['p1','Null id']);assert.equal(await documents.countDocuments(ranged),2);assert.equal((await documents.find({kind:'sale','lines.productId':'prod-a'}).toArray()).length,1);assert.equal((await documents.find({id:null}).toArray()).length,1);assert.equal((await documents.find({$or:[{kind:'purchase'},{partyName:{$regex:'Null'}}]}).toArray()).length,2);const plan=db.native.prepare("EXPLAIN QUERY PLAN SELECT data_json FROM documents WHERE json_extract(data_json,'$.kind')=? AND json_extract(data_json,'$.status')=? AND json_extract(data_json,'$.occurredAt')>=? AND json_extract(data_json,'$.occurredAt')<?").all('sale','posted','2026-09-01T00:00:00.000Z','2026-10-01T00:00:00.000Z');assert.ok(plan.some(row=>String(row.detail).includes('documents_kind_status_time_idx')));const indexes=db.native.prepare("SELECT name FROM sqlite_master WHERE type='index'").all().map(row=>row.name);for(const name of ['documents_kind_status_time_idx','documents_party_status_time_idx','financial_account_time_idx','stock_product_time_idx','products_category_idx','documents_status_time_idx','stock_time_idx','products_expiry_idx'])assert.ok(indexes.includes(name))});
test('candidate filtering preserves missing-field semantics for effective financial rows',async()=>{const movements=db.collection('financialMovements');await movements.insertMany([{id:'m1',documentId:'d1',type:'sale',status:'posted',occurredAt:'2026-09-18T10:00:00.000Z',direction:'in',amount:10},{id:'m2',documentId:'d2',type:'expense',status:'reversed',isReversal:false,occurredAt:'2026-09-18T11:00:00.000Z',direction:'out',amount:2},{id:'m3',documentId:'d3',type:'expense',status:'posted',isReversal:true,occurredAt:'2026-09-18T12:00:00.000Z',direction:'out',amount:3}]);const query={occurredAt:{$gte:'2026-09-18T00:00:00.000Z',$lt:'2026-09-19T00:00:00.000Z'},status:{$ne:'reversed'},isReversal:{$ne:true}};assert.deepEqual((await movements.find(query).toArray()).map(row=>row.id),['m1']);assert.equal(await movements.countDocuments(query),1)});
test('nested product-line and expiry candidates preserve document query semantics',async()=>{const documents=db.collection('documents');await documents.insertMany([{id:'a',status:'posted',lines:[{productId:'p1'},{productId:'p2'}]},{id:'b',status:'posted',lines:[{productId:'p3'}]},{id:'c',status:'posted',lines:[]}]);assert.deepEqual((await documents.find({status:'posted','lines.productId':{$in:['p2','p3']}}).toArray()).map(row=>row.id),['a','b']);assert.deepEqual((await documents.find({status:'posted','lines.productId':{$ne:'p1'}}).toArray()).map(row=>row.id),['b','c']);assert.equal(await documents.countDocuments({status:'posted','lines.productId':'p2'}),1);const products=db.collection('products');await products.insertMany([{id:'old',expiryDate:'2026-01-01',isArchived:false},{id:'future',expiryDate:'2027-01-01',isArchived:false},{id:'none',isArchived:false}]);assert.deepEqual((await products.find({expiryDate:{$type:'string',$lt:'2026-09-19'},isArchived:{$ne:true}}).toArray()).map(row=>row.id),['old'])});

test('safe cursor ordering and paging match the complete filtered dataset',async()=>{const c=db.collection('stockMovements');await c.insertMany(Array.from({length:40},(_,i)=>({id:`row-${String(i).padStart(2,'0')}`,productId:'p',occurredAt:`2026-09-${String(1+(i%20)).padStart(2,'0')}T${String(i%24).padStart(2,'0')}:00:00.000Z`,quantityDelta:i})));const query={productId:'p',occurredAt:{$gte:'2026-09-05T00:00:00.000Z',$lt:'2026-09-20T00:00:00.000Z'}},all=(await c.find(query).toArray()).sort((a,b)=>String(b.occurredAt).localeCompare(String(a.occurredAt))||String(b.id).localeCompare(String(a.id))),paged=await c.find(query).sort({occurredAt:-1,id:-1}).skip(7).limit(9).toArray();assert.deepEqual(paged.map(row=>row.id),all.slice(7,16).map(row=>row.id));assert.deepEqual((await c.find({productId:'p'}).sort({quantityDelta:-1}).skip(3).limit(4).toArray()).map(row=>row.quantityDelta),[36,35,34,33])});


test('financial uniqueness applies only to the effective revision',async()=>{const movements=db.collection('financialMovements');await movements.insertOne({id:'first',documentId:'doc',type:'expense',status:'posted'});await assert.rejects(movements.insertOne({id:'duplicate',documentId:'doc',type:'expense',status:'posted'}),error=>error.code===11000);await movements.updateOne({id:'first'},{$set:{status:'reversed'}});await movements.insertOne({id:'second',documentId:'doc',type:'expense',status:'posted'});await movements.insertOne({id:'audit',documentId:'doc',type:'expense',status:'posted',isReversal:true});assert.equal(await movements.countDocuments({documentId:'doc'}),3)});
test('unsupported adapter operations fail loudly',async()=>{assert.throws(()=>db.collection('products').createIndex({sku:1}),/schema migration/);await db.collection('products').insertOne({id:'x'});await assert.rejects(db.collection('products').updateOne({id:'x'},{$rename:{sku:'code'}}),/Unsupported SQLite update operator/)});
test('insertMany batches large writes while preserving ordered partial failure semantics',async()=>{const c=db.collection('auditEvents');await c.insertMany(Array.from({length:1000},(_,i)=>({id:`bulk-${i}`,value:i})));assert.equal(await c.countDocuments(),1000);await c.insertOne({id:'duplicate'});await assert.rejects(c.insertMany([{id:'before-duplicate'},{id:'duplicate'},{id:'after-duplicate'}]),error=>error.code===11000);assert.ok(await c.findOne({id:'before-duplicate'}));assert.equal(await c.findOne({id:'after-duplicate'}),null)});


test('schema v4 adds product categories and later migrations preserve existing business data',async()=>{await db.collection('products').insertOne({id:'keep-product',sku:'501',name:'Keep me'});db.native.exec('DROP TABLE product_categories; DROP INDEX IF EXISTS financial_document_type_active_unique; DELETE FROM schema_migrations WHERE version>=4;');const {ensureDatabaseSchema}=await import('../lib/sqlite.ts');ensureDatabaseSchema(db.native);assert.equal((await db.collection('products').findOne({id:'keep-product'})).name,'Keep me');await db.collection('productCategories').insertOne({id:'category-1',name:'General'});assert.equal((await db.collection('productCategories').findOne({id:'category-1'})).name,'General');assert.equal(db.native.prepare('SELECT max(version) version FROM schema_migrations').get().version,7)});
