import { requireValidLicense } from "../../../../lib/license.ts";
import { CAPABILITIES, createSession, hashPassword, normalizeUsername, requireCapability, SESSION_COOKIE, sessionCookieOptions, validSameOrigin } from "../../../../lib/auth.ts";
import { getDatabase } from "../../../../lib/sqlite.ts";

const safe=(user:Record<string,unknown>)=>({id:String(user.id),username:String(user.username),name:String(user.name??user.username),isActive:user.isActive===true,permissions:user.owner===true?[...CAPABILITIES]:(Array.isArray(user.permissions)?user.permissions:[]).filter(value=>CAPABILITIES.includes(value as typeof CAPABILITIES[number])),owner:user.owner===true,createdAt:user.createdAt,updatedAt:user.updatedAt});
const permissions=(value:unknown)=>Array.isArray(value)?[...new Set(value.filter(item=>typeof item==="string"&&CAPABILITIES.includes(item as typeof CAPABILITIES[number])))]:[];

export async function GET(request:Request){const licenseDenied=await requireValidLicense();if(licenseDenied)return licenseDenied;const denied=await requireCapability(request,"settings.users.manage");if(denied)return denied;const users=await (await getDatabase()).collection("users").find().sort({owner:-1,createdAt:1}).toArray();return Response.json({users:users.map(safe)},{headers:{"cache-control":"no-store"}})}
export async function POST(request:Request){const licenseDenied=await requireValidLicense();if(licenseDenied)return licenseDenied;const denied=await requireCapability(request,"settings.users.manage");if(denied)return denied;if(!validSameOrigin(request))return Response.json({error:"طلب غير صالح"},{status:403});try{const body=await request.json(),username=String(body.username??"").trim(),usernameNormalized=normalizeUsername(username),password=String(body.password??"");if(!usernameNormalized)return Response.json({error:"اسم المستخدم مطلوب"},{status:400});const db=await getDatabase();if(await db.collection("users").findOne({usernameNormalized}))return Response.json({error:"اسم المستخدم مستخدم بالفعل"},{status:409});const firstUser=await db.collection("users").countDocuments()===0,now=new Date(),user={id:crypto.randomUUID(),username,usernameNormalized,name:String(body.name??username).trim()||username,passwordHash:hashPassword(password),isActive:true,permissions:permissions(body.permissions),owner:false,createdAt:now,updatedAt:now};await db.collection("users").insertOne(user);const headers=firstUser?{"Set-Cookie":`${SESSION_COOKIE}=${createSession({principalType:"user",userId:user.id})}; ${sessionCookieOptions}`} : undefined;return Response.json({user:safe(user)},{status:201,headers})}catch(error){return Response.json({error:error instanceof Error?error.message:"بيانات المستخدم غير صالحة"},{status:400})}}
