import { requireValidLicense } from "../../../../../../lib/license.ts";
import { requireCapability, validSameOrigin } from "../../../../../../lib/auth.ts";
import { buildDataAccImportPackage } from "../../../../../../legacy/dataacc-sqlite.ts";
import { finishLegacyUpload } from "../../../../../../legacy/upload-store.ts";
import { getDatabase } from "../../../../../../lib/sqlite.ts";
import { createLegacyImportRun } from "../../../../../../legacy/import-run.ts";
import { buildImportPreview } from "../../../../../../migration/preview.ts";
export const runtime = "nodejs";
export async function POST(request: Request) {const licenseDenied=await requireValidLicense();if(licenseDenied)return licenseDenied; const denied=await requireCapability(request,"settings.legacy.import");if(denied)return denied;if(!validSameOrigin(request))return Response.json({error:"طلب غير صالح"},{status:403});try{const body=await request.json() as {uploadId:string;action:"preview"|"import";stockPolicy?:string;accountBalancePolicy?:string;filename?:string};const bytes=await finishLegacyUpload(body.uploadId),db=await getDatabase();if(body.action==="preview")return Response.json({...await buildImportPreview(db,await buildDataAccImportPackage(bytes,body.filename)),uploadId:body.uploadId});if(body.action!=="import")throw new Error("عملية الرفع غير صالحة");return Response.json(await createLegacyImportRun(db,body.uploadId,body.stockPolicy==="use-imported"?"use-imported":"keep-current",body.accountBalancePolicy==="use-imported"||body.accountBalancePolicy==="adjustment"?body.accountBalancePolicy:"keep-current",body.filename),{status:202});}catch(e){console.error("External import upload failed",e);return Response.json({error:e instanceof Error&&e.message.includes("نسخة أمان")?e.message:"تعذرت قراءة ملف SQLite. تأكد من صحة الملف ثم حاول مرة أخرى."},{status:400});} }
