export type ExcelCell = string | number | boolean | null | undefined;
export type ExcelSheet = { name: string; rows: ExcelCell[][]; rtl?: boolean };

const encoder = new TextEncoder();
const esc = (v: unknown) => String(v ?? "").replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;").replaceAll('"', "&quot;");
const col = (i: number) => { let s = "", n = i + 1; while (n) { n--; s = String.fromCharCode(65 + n % 26) + s; n = Math.floor(n / 26); } return s; };
const cell = (v: ExcelCell, r: number, c: number) => { const ref=`${col(c)}${r+1}`, style=r===0?' s="1"':''; if(typeof v==="number"&&Number.isFinite(v))return `<c r="${ref}"${style}><v>${v}</v></c>`; if(typeof v==="boolean")return `<c r="${ref}" t="b"${style}><v>${v?1:0}</v></c>`; return `<c r="${ref}" t="inlineStr"${style}><is><t xml:space="preserve">${esc(v)}</t></is></c>`; };
const sheetXml=(s:ExcelSheet)=>`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetViews><sheetView workbookViewId="0"${s.rtl===false?'':' rightToLeft="1"'}/></sheetViews><sheetData>${s.rows.map((row,r)=>`<row r="${r+1}">${row.map((v,c)=>cell(v,r,c)).join('')}</row>`).join('')}</sheetData></worksheet>`;
const clean=(v:string,f:string)=>v.replace(/[\\/*?:[\]]/g,' ').replace(/\s+/g,' ').trim().slice(0,31)||f;
const styles=`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><styleSheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><fonts count="2"><font><sz val="11"/><name val="Arial"/></font><font><b/><sz val="11"/><name val="Arial"/></font></fonts><fills count="2"><fill><patternFill patternType="none"/></fill><fill><patternFill patternType="gray125"/></fill></fills><borders count="1"><border><left/><right/><top/><bottom/><diagonal/></border></borders><cellStyleXfs count="1"><xf numFmtId="0" fontId="0" fillId="0" borderId="0"/></cellStyleXfs><cellXfs count="2"><xf numFmtId="0" fontId="0" fillId="0" borderId="0" xfId="0"/><xf numFmtId="0" fontId="1" fillId="0" borderId="0" xfId="0" applyFont="1"/></cellXfs><cellStyles count="1"><cellStyle name="Normal" xfId="0" builtinId="0"/></cellStyles></styleSheet>`;
const table=(()=>{const t=new Uint32Array(256);for(let n=0;n<256;n++){let c=n;for(let k=0;k<8;k++)c=(c&1)?0xedb88320^(c>>>1):c>>>1;t[n]=c>>>0}return t})();
const crc=(b:Uint8Array)=>{let c=0xffffffff;for(const x of b)c=table[(c^x)&255]^(c>>>8);return(c^0xffffffff)>>>0};
const u16=(v:number)=>new Uint8Array([v&255,(v>>>8)&255]),u32=(v:number)=>new Uint8Array([v&255,(v>>>8)&255,(v>>>16)&255,(v>>>24)&255]);
const join=(a:Uint8Array[])=>{const z=new Uint8Array(a.reduce((n,x)=>n+x.length,0));let o=0;for(const x of a){z.set(x,o);o+=x.length}return z};
function zip(files:Array<{path:string,data:Uint8Array}>){const locals:Uint8Array[]=[],centrals:Uint8Array[]=[];let off=0;for(const f of files){const n=encoder.encode(f.path),x=crc(f.data),local=join([u32(0x04034b50),u16(20),u16(0x0800),u16(0),u16(0),u16(0),u32(x),u32(f.data.length),u32(f.data.length),u16(n.length),u16(0),n,f.data]);locals.push(local);centrals.push(join([u32(0x02014b50),u16(20),u16(20),u16(0x0800),u16(0),u16(0),u16(0),u32(x),u32(f.data.length),u32(f.data.length),u16(n.length),u16(0),u16(0),u16(0),u16(0),u32(0),u32(off),n]));off+=local.length}const body=join(locals),central=join(centrals);return join([body,central,u32(0x06054b50),u16(0),u16(0),u16(files.length),u16(files.length),u32(central.length),u32(body.length),u16(0)])}
export function createXlsx(input:ExcelSheet[]){const used=new Set<string>();const sheets=input.filter(s=>s.rows.length).map((s,i)=>{const base=clean(s.name,`Sheet ${i+1}`);let name=base,n=2;while(used.has(name))name=`${base.slice(0,27)} ${n++}`;used.add(name);return{...s,name}});if(!sheets.length)sheets.push({name:'Sheet 1',rows:[['No data']],rtl:false});const types=`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml"/>${sheets.map((_,i)=>`<Override PartName="/xl/worksheets/sheet${i+1}.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/>`).join('')}</Types>`;const root=`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>`;const book=`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets>${sheets.map((s,i)=>`<sheet name="${esc(s.name)}" sheetId="${i+1}" r:id="rId${i+1}"/>`).join('')}</sheets></workbook>`;const rels=`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">${sheets.map((_,i)=>`<Relationship Id="rId${i+1}" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet${i+1}.xml"/>`).join('')}<Relationship Id="rId${sheets.length+1}" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/></Relationships>`;return zip([{path:'[Content_Types].xml',data:encoder.encode(types)},{path:'_rels/.rels',data:encoder.encode(root)},{path:'xl/workbook.xml',data:encoder.encode(book)},{path:'xl/_rels/workbook.xml.rels',data:encoder.encode(rels)},{path:'xl/styles.xml',data:encoder.encode(styles)},...sheets.map((s,i)=>({path:`xl/worksheets/sheet${i+1}.xml`,data:encoder.encode(sheetXml(s))}))])}
