import { createHash, createHmac, timingSafeEqual, webcrypto } from "node:crypto";
import { execFile } from "node:child_process";
import { mkdir, open, readFile, rename, unlink, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { promisify } from "node:util";
import { log } from "./log.ts";
import { LICENSE_ALGORITHM, LICENSE_KEY_ID, LICENSE_V2_KEY_ID, PUBLIC_LICENSE_KEYS } from "./license-public-key.ts";

export const MAX_LICENSE_BYTES=64*1024,LICENSE_FILENAME="license.alkarna-license",ROLLBACK_TOLERANCE_MS=120000;
const DEVICE_ERROR="تعذر استخراج رقم الجهاز. تواصل مع الدعم.",execFileAsync=promisify(execFile),PERSIST_INTERVAL_MS=7000;
export type LicensePayloadV1={licenseId:string;storeId:string;customerName:string;storeName:string;deviceId:string;edition:string;type:"perpetual";issuedAt:string;notes:string};
export type LicensePayloadV2={licenseId:string;storeId:string;customerName:string;storeName:string;deviceId:string;edition:"desktop";type:"perpetual"|"temporary";durationSeconds:number|null;activationMode:"single-install";notes:string};
export type LicensePayload=LicensePayloadV1|LicensePayloadV2;
export type LicenseDocument={schema:string;version:number;keyId:string;algorithm:string;payload:LicensePayload;signature:string};
export type LicenseInfo={licenseId:string;storeId:string;customerName:string;storeName:string;deviceId:string;type:"perpetual"|"temporary";durationSeconds:number|null;remainingSeconds:number|null;issuedAt?:string};
export type LicenseStatus={valid:false;reason?:string;code?:string}|{valid:true;license:LicenseInfo};
export type LicenseClock={wallNow:()=>number;monotonicNow:()=>bigint};
type ActiveLicense={licenseId:string;type:"perpetual"|"temporary";durationSeconds:number|null;remainingMs:number|null;lastWallClockMs:number;expired:boolean;clockRollbackDetected:boolean};
type Ledger={stateVersion:2;deviceId:string;consumedLicenseIds:string[];activeLicense:ActiveLicense|null};
type Runtime={licenseId:string;checkpointRemainingMs:number;checkpointWallClockMs:number;checkpointMonotonicNs:bigint};
export class LicenseError extends Error{constructor(message:string,public status=400,public code="LICENSE_INVALID"){super(message)}}
export const systemLicenseClock:LicenseClock={wallNow:Date.now,monotonicNow:()=>process.hrtime.bigint()};
const normalizeClock=(clock:LicenseClock|(()=>number)=systemLicenseClock):LicenseClock=>typeof clock==="function"?{wallNow:clock,monotonicNow:()=>BigInt(Math.trunc(clock()*1e6))}:clock;
export function canonicalLicensePayload(p:LicensePayloadV1){return JSON.stringify({licenseId:p.licenseId,storeId:p.storeId,customerName:p.customerName,storeName:p.storeName,deviceId:p.deviceId,edition:p.edition,type:p.type,issuedAt:p.issuedAt,notes:p.notes})}
export function canonicalLicensePayloadV2(p:LicensePayloadV2){return JSON.stringify({licenseId:p.licenseId,storeId:p.storeId,customerName:p.customerName,storeName:p.storeName,deviceId:p.deviceId,edition:p.edition,type:p.type,durationSeconds:p.durationSeconds,activationMode:p.activationMode,notes:p.notes})}
export function formatDeviceCode(guid:string){const n=guid.trim().toLowerCase().replace(/[{}]/g,"");if(!n)throw new LicenseError(DEVICE_ERROR,500);const d=createHash("sha256").update(`mr.alkarna.desktop|device-v1|${n}`).digest("hex").slice(0,20).toUpperCase();return `AKD-${d.match(/.{1,4}/g)!.join("-")}`}
export async function getDeviceId(){if(process.env.NODE_ENV==="test"&&process.env.ALKARNA_TEST_DEVICE_ID){const v=process.env.ALKARNA_TEST_DEVICE_ID.trim();return /^AKD-(?:[A-F0-9]{4}-){4}[A-F0-9]{4}$/.test(v)?v:formatDeviceCode(v)}if(process.platform!=="win32")throw new LicenseError(DEVICE_ERROR,500);try{const {stdout}=await execFileAsync("reg.exe",["query","HKLM\\SOFTWARE\\Microsoft\\Cryptography","/v","MachineGuid"],{windowsHide:true,timeout:5000});const m=stdout.match(/MachineGuid\s+REG_SZ\s+([^\r\n]+)/i);if(!m?.[1])throw Error();return formatDeviceCode(m[1])}catch(error){log("error","license.device.failed",{error});throw new LicenseError(DEVICE_ERROR,500)}}
export function getLicensePath(){return join(process.env.ALKARNA_USER_DATA??join(process.cwd(),".dev-data"),"config",LICENSE_FILENAME)}
export function getLicenseStatePath(){return process.env.ALKARNA_LICENSE_STATE_PATH??join(process.env.LOCALAPPDATA??join(process.env.HOME??process.cwd(),".local","share"),"PayZone","AlKarna-Licensing","state-v2.json")}
const registryKey="HKCU\\Software\\PayZone\\AlKarna\\Licensing\\v2",registryValue="State";
function strictSignature(v:unknown){if(typeof v!=="string"||!/^[A-Za-z0-9_-]+$/.test(v)||v.length%4===1)throw new LicenseError("تعذر التحقق من توقيع الترخيص");const b=Buffer.from(v,"base64url");if(b.length!==64||b.toString("base64url")!==v)throw new LicenseError("تعذر التحقق من توقيع الترخيص");return b}
const required=(v:unknown)=>typeof v==="string"&&v.trim().length>0;
const validIso=(v:unknown):v is string=>typeof v==="string"&&/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d{1,3})?(?:Z|[+-]\d{2}:\d{2})$/.test(v)&&Number.isFinite(Date.parse(v));
export function parseLicenseFile(content:string|Uint8Array){if((typeof content==="string"?Buffer.byteLength(content):content.byteLength)>MAX_LICENSE_BYTES)throw new LicenseError("ملف الترخيص أكبر من الحد المسموح",413);try{const v=JSON.parse(typeof content==="string"?content:Buffer.from(content).toString());if(!v||typeof v!=="object"||Array.isArray(v))throw Error();return v as LicenseDocument}catch{throw new LicenseError("ملف الترخيص غير مدعوم")}}
async function verifySignature(doc:LicenseDocument,canonical:string,keys:Record<string,JsonWebKey>){let valid=false;try{const key=await webcrypto.subtle.importKey("jwk",keys[doc.keyId],{name:"ECDSA",namedCurve:"P-256"},false,["verify"]);valid=await webcrypto.subtle.verify({name:"ECDSA",hash:"SHA-256"},key,strictSignature(doc.signature),new TextEncoder().encode(canonical))}catch{}if(!valid)throw new LicenseError("تعذر التحقق من توقيع الترخيص")}
async function verifyV1(doc:LicenseDocument,device:string,keys:Record<string,JsonWebKey>){const p=doc.payload as LicensePayloadV1;if(doc.keyId!==LICENSE_KEY_ID||!keys[doc.keyId]||!p||![p.licenseId,p.storeId,p.customerName,p.storeName,p.deviceId,p.edition,p.type,p.issuedAt].every(required)||typeof p.notes!=="string"||p.edition!=="desktop"||p.type!=="perpetual"||!validIso(p.issuedAt))throw new LicenseError("هذا الترخيص غير صالح");await verifySignature(doc,canonicalLicensePayload(p),keys);if(p.deviceId!==device)throw new LicenseError("هذا الترخيص مخصص لجهاز آخر");return doc}
async function verifyV2(doc:LicenseDocument,device:string,keys:Record<string,JsonWebKey>){const p=doc.payload as LicensePayloadV2,fields=["licenseId","storeId","customerName","storeName","deviceId","edition","type","durationSeconds","activationMode","notes"],exactFields=p&&Object.keys(p).length===fields.length&&fields.every(field=>Object.hasOwn(p,field));const durationValid=p?.type==="perpetual"?p.durationSeconds===null:Number.isSafeInteger(p?.durationSeconds)&&Number(p.durationSeconds)>0;if(doc.keyId!==LICENSE_V2_KEY_ID||!keys[doc.keyId]||!p||!exactFields||![p.licenseId,p.storeId,p.customerName,p.storeName,p.deviceId].every(required)||typeof p.notes!=="string"||p.edition!=="desktop"||!(p.type==="perpetual"||p.type==="temporary")||!durationValid||p.activationMode!=="single-install")throw new LicenseError("هذا الترخيص غير صالح");await verifySignature(doc,canonicalLicensePayloadV2(p),keys);if(p.deviceId!==device)throw new LicenseError("هذا الترخيص مخصص لجهاز آخر");return doc}
export async function verifyLicenseFile(content:string|Uint8Array,currentDeviceId?:string,keys?:Record<string,JsonWebKey>,_clock?:LicenseClock|(()=>number),_persist=true){void _persist;const device=currentDeviceId??await getDeviceId(),doc=parseLicenseFile(content),all=keys??PUBLIC_LICENSE_KEYS as unknown as Record<string,JsonWebKey>;if(doc.schema!=="alkarna-license"||doc.algorithm!==LICENSE_ALGORITHM||!all[doc.keyId])throw new LicenseError("ملف الترخيص غير مدعوم");if(doc.version===1)return verifyV1(doc,device,all);if(doc.version===2)return verifyV2(doc,device,all);throw new LicenseError("ملف الترخيص غير مدعوم")}

const emptyLedger=(device:string):Ledger=>({stateVersion:2,deviceId:device,consumedLicenseIds:[],activeLicense:null});
const stateKey=(device:string)=>createHash("sha256").update(`PayZone|AlKarna|licensing-state-v2|${device}`).digest();
function encodeLedger(value:Ledger){const payload=Buffer.from(JSON.stringify(value)).toString("base64url"),mac=createHmac("sha256",stateKey(value.deviceId)).update(payload).digest("base64url");return JSON.stringify({format:"alkarna-state-v2",payload,mac})}
function parseLedger(text:string|null,device:string){try{const envelope=JSON.parse(text??""),payload=String(envelope.payload??""),given=Buffer.from(String(envelope.mac??""),"base64url"),expected=createHmac("sha256",stateKey(device)).update(payload).digest();if(envelope.format!=="alkarna-state-v2"||given.length!==expected.length||!timingSafeEqual(given,expected))return null;const x=JSON.parse(Buffer.from(payload,"base64url").toString());if(x.stateVersion===2&&x.deviceId===device&&Array.isArray(x.consumedLicenseIds)&&(x.activeLicense===null||validActive(x.activeLicense)))return x as Ledger}catch{}return null}
function validActive(x:ActiveLicense){return required(x.licenseId)&&(x.type==="perpetual"||x.type==="temporary")&&(x.durationSeconds===null||Number.isSafeInteger(x.durationSeconds))&&(x.remainingMs===null||Number.isFinite(x.remainingMs))&&Number.isFinite(x.lastWallClockMs)&&typeof x.expired==="boolean"&&typeof x.clockRollbackDetected==="boolean"}
async function readRegistry(){if(process.platform!=="win32"||process.env.ALKARNA_LICENSE_DISABLE_REGISTRY==="1")return null;try{const {stdout}=await execFileAsync("reg.exe",["query",registryKey,"/v",registryValue],{windowsHide:true});return stdout.match(/State\s+REG_SZ\s+([^\r\n]+)/i)?.[1]??null}catch{return null}}
async function writeRegistry(value:string){if(process.platform!=="win32"||process.env.ALKARNA_LICENSE_DISABLE_REGISTRY==="1")return;await execFileAsync("reg.exe",["add",registryKey,"/v",registryValue,"/t","REG_SZ","/d",Buffer.from(value).toString("base64url"),"/f"],{windowsHide:true})}
function restrictiveActive(a:ActiveLicense|null,b:ActiveLicense|null){if(!a)return b;if(!b)return a;if(a.licenseId!==b.licenseId){const restrictive=a.expired||a.clockRollbackDetected?a:b;return restrictive}return{...a,durationSeconds:a.durationSeconds??b.durationSeconds,remainingMs:a.remainingMs===null?b.remainingMs:b.remainingMs===null?a.remainingMs:Math.min(a.remainingMs,b.remainingMs),lastWallClockMs:Math.max(a.lastWallClockMs,b.lastWallClockMs),expired:a.expired||b.expired,clockRollbackDetected:a.clockRollbackDetected||b.clockRollbackDetected}}
function mergeLedgers(a:Ledger,b:Ledger):Ledger{return{stateVersion:2,deviceId:a.deviceId,consumedLicenseIds:[...new Set([...a.consumedLicenseIds,...b.consumedLicenseIds])],activeLicense:restrictiveActive(a.activeLicense,b.activeLicense)}}
async function persistLedger(l:Ledger){const value=encodeLedger(l),path=getLicenseStatePath();await mkdir(dirname(path),{recursive:true});await writeFile(`${path}.tmp`,value,{mode:0o600});await rename(`${path}.tmp`,path);await writeRegistry(value)}
async function loadLedger(device:string){const [file,regRaw]=await Promise.all([readFile(getLicenseStatePath(),"utf8").catch(()=>null),readRegistry()]),reg=regRaw?Buffer.from(regRaw,"base64url").toString():null,a=parseLedger(file,device),b=parseLedger(reg,device),result=a&&b?mergeLedgers(a,b):a??b??emptyLedger(device);if(!a||(!b&&process.platform==="win32")||(a&&b&&JSON.stringify(a)!==JSON.stringify(result)))await persistLedger(result);return result}
let memoryLedger:Ledger|undefined,runtime:Runtime|undefined,lastPersistedMonotonic=BigInt(0),persistTimer:ReturnType<typeof setInterval>|undefined;
export function resetLicenseRuntimeState(){memoryLedger=undefined;runtime=undefined;lastPersistedMonotonic=BigInt(0);if(persistTimer)clearInterval(persistTimer);persistTimer=undefined}
async function ledger(device:string){if(!memoryLedger||memoryLedger.deviceId!==device)memoryLedger=await loadLedger(device);return memoryLedger}
function licenseFailure(active:ActiveLicense){if(active.expired)return new LicenseError("انتهت صلاحية الترخيص",402,"LICENSE_EXPIRED");if(active.clockRollbackDetected)return new LicenseError("تم اكتشاف تغيير غير صالح في تاريخ أو وقت الجهاز.",402,"LICENSE_CLOCK_ROLLBACK");return null}
async function persistEvaluation(l:Ledger,clock:LicenseClock,force=false){if(!l.activeLicense)return;const nowMono=clock.monotonicNow();if(force||nowMono-lastPersistedMonotonic>=BigInt(PERSIST_INTERVAL_MS)*BigInt(1000000)){await persistLedger(l);lastPersistedMonotonic=nowMono}}
async function evaluateTemporary(l:Ledger,clock:LicenseClock,force=false){const a=l.activeLicense!;const terminal=licenseFailure(a);if(terminal)throw terminal;const wall=clock.wallNow(),mono=clock.monotonicNow();if(!runtime||runtime.licenseId!==a.licenseId){if(wall+ROLLBACK_TOLERANCE_MS<a.lastWallClockMs){a.clockRollbackDetected=true;await persistEvaluation(l,clock,true);throw licenseFailure(a)!}const closedElapsed=Math.max(0,wall-a.lastWallClockMs);a.remainingMs=Math.max(0,(a.remainingMs??0)-closedElapsed);a.lastWallClockMs=Math.max(a.lastWallClockMs,wall);runtime={licenseId:a.licenseId,checkpointRemainingMs:a.remainingMs,checkpointWallClockMs:wall,checkpointMonotonicNs:mono}}else{if(wall+ROLLBACK_TOLERANCE_MS<runtime.checkpointWallClockMs||wall+ROLLBACK_TOLERANCE_MS<a.lastWallClockMs){a.clockRollbackDetected=true;await persistEvaluation(l,clock,true);throw licenseFailure(a)!}const monotonicElapsed=Math.max(0,Number(mono-runtime.checkpointMonotonicNs)/1e6),wallElapsed=Math.max(0,wall-runtime.checkpointWallClockMs),effectiveElapsed=Math.max(monotonicElapsed,wallElapsed);a.remainingMs=Math.max(0,runtime.checkpointRemainingMs-effectiveElapsed);a.lastWallClockMs=Math.max(a.lastWallClockMs,wall)}if((a.remainingMs??0)<=0){a.remainingMs=0;a.expired=true;await persistEvaluation(l,clock,true);throw licenseFailure(a)!}await persistEvaluation(l,clock,force);return a.remainingMs!}
function ensureTimer(clock:LicenseClock){if(persistTimer)return;persistTimer=setInterval(()=>{if(memoryLedger?.activeLicense?.type==="temporary")void evaluateTemporary(memoryLedger,clock,true).catch(()=>{})},PERSIST_INTERVAL_MS);persistTimer.unref?.()}
const info=(p:LicensePayload,remainingSeconds:number|null=null):LicenseInfo=>({licenseId:p.licenseId,storeId:p.storeId,customerName:p.customerName,storeName:p.storeName,deviceId:p.deviceId,type:p.type,durationSeconds:"durationSeconds" in p?p.durationSeconds:null,remainingSeconds,issuedAt:"issuedAt" in p?p.issuedAt:undefined});
export async function readInstalledLicense(){try{return await readFile(getLicensePath(),"utf8")}catch{return null}}
export async function getLicenseStatus(clockInput:LicenseClock|(()=>number)=systemLicenseClock,currentDeviceId?:string,keys?:Record<string,JsonWebKey>):Promise<LicenseStatus>{const content=await readInstalledLicense();if(!content)return{valid:false};try{const device=currentDeviceId??await getDeviceId(),d=await verifyLicenseFile(content,device,keys),clock=normalizeClock(clockInput);if(d.version===1)return{valid:true,license:info(d.payload)};const l=await ledger(device),a=l.activeLicense;if(!a||a.licenseId!==d.payload.licenseId)return{valid:false,reason:"يجب تفعيل ترخيص الجهاز",code:"LICENSE_REQUIRED"};let remaining:null|number=null;if(a.type==="temporary"){remaining=await evaluateTemporary(l,clock);ensureTimer(clock)}else{const failure=licenseFailure(a);if(failure)throw failure}return{valid:true,license:info(d.payload,remaining===null?null:Math.max(0,Math.ceil(remaining/1000)))}}catch(e){return{valid:false,reason:e instanceof Error?e.message:"هذا الترخيص غير صالح",code:e instanceof LicenseError?e.code:"LICENSE_INVALID"}}}
export async function requireValidLicense(){const test=process.execArgv.includes("--test")||process.env.NODE_TEST_CONTEXT!==undefined;if(test&&process.env.ALKARNA_TEST_LICENSE_BYPASS==="1")return null;const s=await getLicenseStatus();return s.valid?null:Response.json({error:s.reason??"يجب تفعيل ترخيص الجهاز",code:s.code??"LICENSE_REQUIRED"},{status:402})}
export async function installLicense(content:string|Uint8Array,currentDeviceId?:string,keys?:Record<string,JsonWebKey>,clockInput:LicenseClock|(()=>number)=systemLicenseClock){const device=currentDeviceId??await getDeviceId(),doc=await verifyLicenseFile(content,device,keys),path=getLicensePath(),clock=normalizeClock(clockInput);if(doc.version===2){const l=await ledger(device),p=doc.payload as LicensePayloadV2;if(l.consumedLicenseIds.includes(p.licenseId))throw new LicenseError("تم استخدام ملف التفعيل مسبقًا على هذا الجهاز.",409,"LICENSE_ALREADY_USED");const prepared=`${path}.${process.pid}.prepared`;await mkdir(dirname(path),{recursive:true});await writeFile(prepared,typeof content==="string"?content:Buffer.from(content),{mode:0o600});const now=clock.wallNow();l.consumedLicenseIds.push(p.licenseId);l.activeLicense={licenseId:p.licenseId,type:p.type,durationSeconds:p.durationSeconds,remainingMs:p.type==="temporary"?p.durationSeconds!*1000:null,lastWallClockMs:now,expired:false,clockRollbackDetected:false};runtime=p.type==="temporary"?{licenseId:p.licenseId,checkpointRemainingMs:p.durationSeconds!*1000,checkpointWallClockMs:now,checkpointMonotonicNs:clock.monotonicNow()}:undefined;await persistLedger(l).catch(async e=>{await unlink(prepared).catch(()=>{});throw e});await rename(prepared,path);if(p.type==="temporary")ensureTimer(clock)}else{await mkdir(dirname(path),{recursive:true});const tmp=`${path}.${process.pid}.tmp`,h=await open(tmp,"wx",0o600);try{await writeFile(h,typeof content==="string"?content:Buffer.from(content));await h.sync()}finally{await h.close()}await rename(tmp,path)}log("info","license.install.success",{licenseId:doc.payload.licenseId});return info(doc.payload,doc.version===2&&doc.payload.type==="temporary"?(doc.payload as LicensePayloadV2).durationSeconds:null)}
