import initSqlJs, { type Database } from "sql.js";
import { createRequire } from "node:module";
import { isAbsolute, join } from "node:path";
import type { AnyBulkWriteOperation, Db, Document } from "mongodb";
import { rebuildCounters } from "../lib/backup.ts";
import { createHash } from "node:crypto";
import type { CanonicalEntity, CanonicalImportPackage, ImportSourceAdapter } from "../migration/types.ts";
import type { AccountBalancePolicy } from "../migration/types.ts";
import { normalizeImportText } from "../migration/matching.ts";

export const SQLITE_MAGIC = Buffer.from("SQLite format 3\0", "ascii");
export const MAX_LEGACY_BYTES = 50 * 1024 * 1024;
export const LEGACY_SUPPORTED_TABLES = ["itemsTB","storesTB","stores_itemsTB","customerTB","supplierTB","suppliersTB","BankTB","PayMethods","buyBillTB","items_BuyTB","purchBillTB","items_purchTB","safeTB","process_TypeTB","process_MainType","companyTB"];
const financialReview = ["tblBankDeposit","tblBankConvert","tblBankConvertToSafe","customerAccountTB","customerSolfaTB","suppliersAccountTB","suppliersSolfaTB"];
const unsupported = ["userTB","authTB","EmpTBs","Emp_salaryTB","Emp_mrtbatTB","presenceTB","MaintainceTB","tblPrinter","tblPrinterAccounts","Units","items_UnitsTB","NotesTB","ShowBillTB","items_ShowBillTB"];
export function detectLegacyDatabase(bytes: Uint8Array) { return bytes.length >= 16 && Buffer.from(bytes.subarray(0, 16)).equals(SQLITE_MAGIC); }

/** Resolve the actual runtime asset through Node's package resolver (including standalone deployments). */
export function resolveSqlJsWasmPath() {
  const runtimeRequire = createRequire(join(process.cwd(), "package.json"));
  const wasmPath = runtimeRequire.resolve("sql.js/dist/sql-wasm.wasm");
  if (!isAbsolute(wasmPath)) throw new Error("sql.js WASM path must be absolute");
  return wasmPath;
}

async function open(bytes: Uint8Array) { if (bytes.byteLength > MAX_LEGACY_BYTES) throw new Error("ملف SQLite أكبر من الحد المسموح"); if (!detectLegacyDatabase(bytes)) throw new Error("الملف ليس قاعدة SQLite 3"); const SQL = await initSqlJs({ locateFile: () => resolveSqlJsWasmPath() }); return new SQL.Database(bytes); }
type Row = Record<string, unknown>;
const tables = (db: Database):string[] => db.exec("SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%'")[0]?.values.flat().map(String) ?? [];
const quote = (name: string) => `"${name.replaceAll('"','""')}"`;
function rows(db: Database, table: string): Row[] { const result = db.exec(`SELECT * FROM ${quote(table)}`)[0]; return result ? result.values.map(values => Object.fromEntries(result.columns.map((c,i)=>[c, values[i]]))) : []; }
const get = (r: Row, ...names: string[]) => { const map = new Map(Object.entries(r).map(([k,v])=>[k.toLowerCase(),v])); for (const n of names) if (map.has(n.toLowerCase())) return map.get(n.toLowerCase()); return null; };
const text = (v: unknown) => v == null ? "" : String(v).trim(); const num = (v: unknown) => { const n=Number(v); return Number.isFinite(n)?n:0; };
const date = (v: unknown) => { const raw=text(v), deterministic=/^\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}$/.test(raw)?`${raw.replace(" ","T")}Z`:raw; const d=new Date(deterministic); return Number.isNaN(d.valueOf()) ? new Date(0).toISOString() : d.toISOString(); };
const normalize = (v: unknown) => text(v).toLocaleLowerCase("ar").replace(/\s+/g," ");
const key = (table:string,id:unknown) => `dataacc:${table}:${text(id)}`;
const id = (prefix:string, legacyKey:string) => `${prefix}-legacy-${Buffer.from(legacyKey).toString("base64url")}`;
const count = (db:Database, available:Set<string>, name:string) => available.has(name)?rows(db,name).length:0;
export type LegacyPreview = { format:"dataacc-sqlite"; groups:Array<{key:string;label:string;count:number;status:"ready"|"unsupported"|"review"}>; warnings:string[]; tables:string[] };
export async function inspectLegacyDatabase(bytes: Uint8Array): Promise<LegacyPreview> { const db=await open(bytes); try { const names=tables(db), a=new Set(names); const groups=[
 ["products","المنتجات",count(db,a,"itemsTB"),"ready"],["warehouses","المخازن",count(db,a,"storesTB"),"ready"],["stocks","أرصدة المخازن",count(db,a,"stores_itemsTB"),"ready"],["sales","فواتير البيع",count(db,a,"buyBillTB"),"ready"],["saleLines","عناصر فواتير البيع",count(db,a,"items_BuyTB"),"ready"],["purchases","فواتير الشراء",count(db,a,"purchBillTB"),"ready"],["purchaseLines","عناصر الشراء",count(db,a,"items_purchTB"),"ready"],["parties","العملاء والموردون",count(db,a,"customerTB")+count(db,a,a.has("suppliersTB")?"suppliersTB":"supplierTB"),"ready"],["accounts","الحسابات والبنوك",count(db,a,"BankTB"),"ready"],["expenses","المصاريف",count(db,a,"safeTB"),"ready"],
 ...unsupported.filter(x=>a.has(x)).map(x=>[x,x.includes("user")||x==="authTB"?"مستخدمون وصلاحيات النظام السابق":x.includes("Emp")||x==="presenceTB"?"بيانات الموظفين القديمة":x.includes("Printer")?"إعدادات الطباعة القديمة":"بيانات تشغيلية غير مطلوبة",count(db,a,x),"unsupported"]), ...financialReview.filter(x=>a.has(x)).map(x=>[x,x.includes("Bank")?"حركة بنكية قديمة":"حركة حساب طرف قديمة",count(db,a,x),"review"])
 ].map(([key,label,count,status])=>({key:String(key),label:String(label),count:Number(count),status:status as "ready"|"unsupported"|"review"})); return {format:"dataacc-sqlite",groups,warnings:financialReview.filter(x=>a.has(x)).map(x=>`${x}: بيانات مالية تحتاج مراجعة — لن يتم استيرادها تلقائيًا`),tables:names}; } finally { db.close(); } }

/** DataAcc is source-specific only here: everything after this boundary consumes canonical entities. */
export async function buildDataAccImportPackage(bytes:Uint8Array,filename?:string):Promise<CanonicalImportPackage>{
 const db=await open(bytes);try{const available=new Set(tables(db)),read=(table:string)=>available.has(table)?rows(db,table):[],entity=(table:string,r:Row,fields:Partial<CanonicalEntity>):CanonicalEntity=>{const sourceId=text(get(r,"id"));return{sourceKey:key(table,sourceId),sourceTable:table,sourceId,...fields}};
 const products=read("itemsTB").map(r=>entity("itemsTB",r,{name:text(get(r,"title")),normalizedName:normalizeImportText(get(r,"title")),barcode:text(get(r,"barcode","code")),data:r}));
 const warehouses=read("storesTB").map(r=>entity("storesTB",r,{name:text(get(r,"title","name","StoreName")),normalizedName:normalizeImportText(get(r,"title","name","StoreName")),data:r}));
 const parties:Array<CanonicalEntity>=[];for(const [table,role] of [["customerTB","customer"],[available.has("suppliersTB")?"suppliersTB":"supplierTB","supplier"]] as const)for(const r of read(table))parties.push(entity(table,r,{name:text(get(r,"title","name","CustomerName","SupplierName")),normalizedName:normalizeImportText(get(r,"title","name","CustomerName","SupplierName")),phone:text(get(r,"phone","tel","mobile")),role,data:r}));
 const paymentAccounts=read("BankTB").map(r=>entity("BankTB",r,{name:text(get(r,"BankName","title","name")),normalizedName:normalizeImportText(get(r,"BankName","title","name")),balance:num(get(r,"rasid")),data:r}));
 const simple=(table:string)=>read(table).map(r=>entity(table,r,{data:r}));const stockBalances=read("stores_itemsTB").map(r=>entity("stores_itemsTB",r,{quantity:num(get(r,"qty")),productSourceKey:key("itemsTB",get(r,"item_idFK")),warehouseSourceKey:key("storesTB",get(r,"store_idFK")),data:r}));
 const entities={products,warehouses,stockBalances,parties,paymentAccounts,financialMovements:[],sales:simple("buyBillTB"),purchases:simple("purchBillTB"),expenses:simple("safeTB")};
 const unknownGroups=financialReview.filter(table=>available.has(table)).map(table=>{const values=read(table);return{key:table,label:table.includes("Bank")?"حركة بنكية قديمة":"حركة حساب طرف قديمة",count:values.length,reason:"نوع أو اتجاه الحركة المالية غير مضمون، لذلك لم تُرحّل تلقائيًا.",columns:Object.keys(values[0]??{}),manualMappingSupported:true}});
 return{source:{type:"dataacc-sqlite",filename,fingerprint:createHash("sha256").update(bytes).digest("hex")},entities,unknownGroups,warnings:unknownGroups.map(x=>`${x.label}: ${x.reason}`)};
 }finally{db.close()}}
export const dataAccAdapter:ImportSourceAdapter={type:"dataacc-sqlite",detect:detectLegacyDatabase,inspect:buildDataAccImportPackage};


export const LEGACY_IMPORT_PHASES = ["warehouses","parties","accounts","products","stocks","sales","purchases","expenses","finalize"] as const;
export type LegacyImportPhase = typeof LEGACY_IMPORT_PHASES[number];
export type LegacyPhaseResult = { processed:number; created:number; existing:number; skipped:number; mongoRoundTrips:number };
const chunks = <T>(values:T[], size=300) => Array.from({length:Math.ceil(values.length/size)},(_,i)=>values.slice(i*size,(i+1)*size));
async function bulk(collection:ReturnType<Db["collection"]>, operations:AnyBulkWriteOperation<Document>[]) { for (const batch of chunks(operations)) await collection.bulkWrite(batch as never[],{ordered:false}); return Math.ceil(operations.length/300); }

/** One short, repeatable import phase. Deterministic ids and legacyKey upserts make every phase safe to retry. */
export async function executeLegacyImportPhase(db:Db, bytes:Uint8Array, phase:LegacyImportPhase, stockPolicy:"current"|"imported"="current",accountBalancePolicy:AccountBalancePolicy="keep-current"):Promise<LegacyPhaseResult>{
 const sqlite=await open(bytes), result={processed:0,created:0,existing:0,skipped:0,mongoRoundTrips:0};
 try { const available=new Set(tables(sqlite)), read=(t:string)=>available.has(t)?rows(sqlite,t):[], now=new Date();
  const warehouses=await db.collection("warehouses").find({}).toArray(); result.mongoRoundTrips++;
  const whByLegacy=new Map(warehouses.map(x=>[text(x.legacyKey),String(x._id)])), whByName=new Map(warehouses.map(x=>[normalize(x.name),String(x._id)]));
  const storeRows=read("storesTB"), warehouseMap=new Map<string,string>(); for(const r of storeRows){const old=text(get(r,"id")),lk=key("storesTB",old),name=text(get(r,"title","name","StoreName"))||`مخزن ${old}`;warehouseMap.set(old,whByLegacy.get(lk)??whByName.get(normalize(name))??id("wh",lk));}
  if(!warehouseMap.size){const fallback=warehouses.find(x=>x.isSalesDefault)??warehouses[0];if(fallback)warehouseMap.set("",String(fallback._id));}
  if(phase==="warehouses"){const ops:AnyBulkWriteOperation<Document>[]=storeRows.map(r=>{const old=text(get(r,"id")),lk=key("storesTB",old),name=text(get(r,"title","name","StoreName"))||`مخزن ${old}`,existing=whByLegacy.get(lk)??whByName.get(normalize(name));if(existing){result.existing++;return {updateOne:{filter:{_id:existing as never},update:{$setOnInsert:{legacyKey:lk}},upsert:false}}}result.created++;return {updateOne:{filter:{_id:id("wh",lk) as never},update:{$setOnInsert:{name,isSalesDefault:false,legacyKey:lk,createdAt:now}},upsert:true}}});result.processed=ops.length;result.mongoRoundTrips+=await bulk(db.collection("warehouses"),ops);return result;}
  const parties=await db.collection("parties").find({}).toArray(); result.mongoRoundTrips++; const partyMap=new Map<string,string>();
  const partyRows:Array<{r:Row;table:string;role:string}>=[];for(const [table,role] of [["customerTB","customer"],[available.has("suppliersTB")?"suppliersTB":"supplierTB","supplier"]])for(const r of read(table))partyRows.push({r,table,role});
  for(const {r,table,role} of partyRows){const old=text(get(r,"id")),lk=key(table,old),name=text(get(r,"title","name","CustomerName","SupplierName"))||`${role==="customer"?"عميل":"مورد"} ${old}`,phone=text(get(r,"phone","tel","mobile"));const found=parties.find(x=>x.legacyKey===lk||(x.partyType===role&&((phone&&x.phone===phone)||normalize(x.name)===normalize(name))));partyMap.set(`${role}:${old}`,found?String(found.id):id("party",lk));}
  if(phase==="parties"){const ops=partyRows.map(({r,table,role})=>{const old=text(get(r,"id")),lk=key(table,old),pid=partyMap.get(`${role}:${old}`)!,name=text(get(r,"title","name","CustomerName","SupplierName"))||`${role==="customer"?"عميل":"مورد"} ${old}`,phone=text(get(r,"phone","tel","mobile")),receivable=num(get(r,"Debitor")),payable=num(get(r,"Creditor")),found=parties.some(x=>String(x.id)===pid);if(found)result.existing++;else result.created++;return {updateOne:{filter:{id:pid},update:{$setOnInsert:{id:pid,name,nameNormalized:normalize(name),phone,partyType:role,receivable,payable,net:receivable-payable,legacyKey:lk,legacyOpeningBalance:{receivable,payable},legacy:{source:"dataacc-sqlite",table,id:get(r,"id")},createdAt:now}},upsert:true}}});result.processed=ops.length;result.mongoRoundTrips+=await bulk(db.collection("parties"),ops);return result;}
  const accounts=await db.collection("paymentAccounts").find({}).toArray();result.mongoRoundTrips++;const accountMap=new Map<string,string>(),accountRows=read("BankTB");for(const r of accountRows){const old=text(get(r,"id")),lk=key("BankTB",old),name=text(get(r,"BankName","title","name"))||`حساب ${old}`,found=accounts.find(x=>x.legacyKey===lk||normalize(x.name)===normalize(name));accountMap.set(old,found?String(found.id):id("account",lk));}
  if(phase==="accounts"){const accountOps:AnyBulkWriteOperation<Document>[]=[],movementOps:AnyBulkWriteOperation<Document>[]=[];for(const r of accountRows){const old=text(get(r,"id")),lk=key("BankTB",old),aid=accountMap.get(old)!,name=text(get(r,"BankName","title","name"))||`حساب ${old}`,amount=num(get(r,"rasid")),existingAccount=accounts.find(x=>String(x.id)===aid),found=!!existingAccount;if(found)result.existing++;else result.created++;const current=num(existingAccount?.balance),applyImported=found&&accountBalancePolicy!=="keep-current"&&current!==amount,delta=amount-current;accountOps.push({updateOne:{filter:{id:aid},update:found?(applyImported?{$set:{balance:amount,balanceInitialized:true}}:{$set:{updatedAt:now}}):{$setOnInsert:{id:aid,code:`legacy-${old}`,name,nameNormalized:normalize(name),color:"#64748b",icon:"wallet",isActive:true,balance:amount,balanceInitialized:true,legacyKey:lk,legacyOpeningBalance:amount,createdAt:now}},upsert:!found}});if(!found||applyImported){const movementAmount=found?delta:amount,movementType=found?"legacy-balance-adjustment":"legacy-opening-balance";movementOps.push({updateOne:{filter:{documentId:`legacy-${found?"adjustment":"opening"}:${aid}:${lk}`,type:movementType},update:{$setOnInsert:{id:id("financial",`${lk}:${movementType}`),documentId:`legacy-${found?"adjustment":"opening"}:${aid}:${lk}`,type:movementType,direction:movementAmount>=0?"in":"out",amount:Math.abs(movementAmount),paymentMethod:aid,occurredAt:now.toISOString(),legacyKey:`${lk}:${movementType}`}},upsert:true}})}}result.processed=accountOps.length;result.mongoRoundTrips+=await bulk(db.collection("paymentAccounts"),accountOps)+await bulk(db.collection("financialMovements"),movementOps);return result;}
  const products=await db.collection("products").find({}).toArray();result.mongoRoundTrips++;const productMap=new Map<string,string>(),productRows=read("itemsTB"),usedBarcodes=new Set(products.map(x=>text(x.barcode)).filter(Boolean));let sequence=Math.max(0,...products.map(x=>/^\d+$/.test(text(x.sku))?num(x.sku):0));for(const r of productRows){const old=text(get(r,"id")),lk=key("itemsTB",old),barcode=text(get(r,"barcode"))||text(get(r,"code")),found=products.find(x=>x.legacyKey===lk||(barcode&&x.barcode===barcode));productMap.set(old,found?String(found.id):id("product",lk));}
  if(phase==="products"){const ops=productRows.map(r=>{const old=text(get(r,"id")),lk=key("itemsTB",old),pid=productMap.get(old)!,candidate=text(get(r,"barcode"))||text(get(r,"code")),found=products.some(x=>String(x.id)===pid);if(found)result.existing++;else result.created++;sequence++;const barcode=!found&&candidate&&!usedBarcodes.has(candidate)?candidate:"";if(barcode)usedBarcodes.add(barcode);return {updateOne:{filter:{id:pid},update:{$setOnInsert:{id:pid,name:text(get(r,"title"))||`منتج ${old}`,sku:String(sequence).padStart(4,"0"),barcode,pieceCost:null,piecePrice:num(get(r,"priceUnit"))||null,stocks:{},legacyOpeningCost:num(get(r,"last_cost","start_Cost"))||null,legacyKey:lk,legacy:{source:"dataacc-sqlite",table:"itemsTB",id:get(r,"id"),originalCode:text(get(r,"code"))},createdAt:now}},upsert:true}}});result.processed=ops.length;result.mongoRoundTrips+=await bulk(db.collection("products"),ops);return result;}
  if(phase==="stocks"){const ops:AnyBulkWriteOperation<Document>[]=[],moves:AnyBulkWriteOperation<Document>[]=[];for(const r of read("stores_itemsTB")){const pid=productMap.get(text(get(r,"item_idFK"))),wid=warehouseMap.get(text(get(r,"store_idFK")));if(!pid||!wid){result.skipped++;continue}const qty=num(get(r,"qty")),p=products.find(x=>String(x.id)===pid),current=num((p?.stocks as Row|undefined)?.[wid]),lk=key("stores_itemsTB",get(r,"id")||`${get(r,"store_idFK")}:${get(r,"item_idFK")}`);if(current!==0&&current!==qty&&stockPolicy==="current"){result.existing++;continue}ops.push({updateOne:{filter:{id:pid},update:{$set:{[`stocks.${wid}`]:qty}}}});moves.push({updateOne:{filter:{legacyKey:lk},update:{$setOnInsert:{id:id("movement",lk),legacyKey:lk,documentId:"legacy-opening",documentNumber:"LEG-OPEN",warehouseId:wid,warehouseName:"ترحيل قديم",productId:pid,productName:p?.name??"",type:"legacy-opening",quantityDelta:qty,balanceBefore:0,balanceAfter:qty,occurredAt:now.toISOString()}},upsert:true}});result.created++}result.processed=read("stores_itemsTB").length;result.mongoRoundTrips+=await bulk(db.collection("products"),ops)+await bulk(db.collection("stockMovements"),moves);return result;}
  const documentPhase=async(kind:"sale"|"purchase",head:string,lineTable:string,fk:string,partyRole:string)=>{const existing=new Set((await db.collection("documents").find({legacyKey:{$in:read(head).map(h=>key(head,get(h,"id")))}}).project({legacyKey:1}).toArray()).map(x=>text(x.legacyKey)));result.mongoRoundTrips++;const grouped=new Map<string,Row[]>();for(const l of read(lineTable)){const k=text(get(l,fk));grouped.set(k,[...(grouped.get(k)??[]),l])}const perDay=new Map<string,number>(),ops:AnyBulkWriteOperation<Document>[]=[];for(const h of read(head)){const old=text(get(h,"id")),lk=key(head,old),occurredAt=date(get(h,"Date")),businessDate=occurredAt.slice(0,10);if(existing.has(lk)){result.existing++;continue}const lines=(grouped.get(old)??[]).map(l=>{const quantity=num(get(l,"qty")),unitPrice=num(get(l,kind==="sale"?"price_Buy":"price_purch")),cost=num(get(l,"LastCost"));return{id:id("line",`${lk}:${text(get(l,"id"))}`),productId:productMap.get(text(get(l,"item_idFK")))??null,description:text(get(l,"title")),quantity,unitPrice,lineTotal:Math.round(quantity*unitPrice),...(kind==="sale"?{costAtSale:cost>0?cost:null,grossProfit:cost>0?Math.round(quantity*(unitPrice-cost)):null}:{})}});const calculated=lines.reduce((s,l)=>s+l.lineTotal,0),total=num(get(h,kind==="sale"?"priceBillAfterKhasm":"priceBill","total"))||calculated,paid=num(get(h,"PaidMony")),due=num(get(h,"remainMony"))||Math.max(0,total-paid),seq=(perDay.get(businessDate)??0)+1;perDay.set(businessDate,seq);ops.push({updateOne:{filter:{legacyKey:lk},update:{$setOnInsert:{id:id("document",lk),legacyKey:lk,legacyBillCode:text(get(h,"Billcode")),number:`LEG-${kind==="sale"?"SAL":"PUR"}-${old}`,kind,status:"posted",partyId:partyMap.get(`${partyRole}:${text(get(h,kind==="sale"?"CustomerFK":"SuppFK"))}`)??null,partyName:null,warehouseId:warehouseMap.get(text(get(h,"StoreFK")))??warehouseMap.values().next().value??null,warehouseName:null,destinationWarehouseId:null,destinationWarehouseName:null,parentDocumentId:null,paymentMethod:null,title:null,total,dueTotal:due,paidTotal:paid,occurredAt,businessDate,...(kind==="sale"?{dailySequence:seq}:{}),lines,legacy:{source:"dataacc-sqlite",table:head,id:get(h,"id")}}},upsert:true}});result.created++}result.processed=read(head).length;result.mongoRoundTrips+=await bulk(db.collection("documents"),ops);return result};
  if(phase==="sales")return await documentPhase("sale","buyBillTB","items_BuyTB","BuyFK","customer");if(phase==="purchases")return await documentPhase("purchase","purchBillTB","items_purchTB","purchFK","supplier");
  if(phase==="expenses"){const ops:AnyBulkWriteOperation<Document>[]=[];for(const r of read("safeTB")){const lk=key("safeTB",get(r,"id")),amount=num(get(r,"QtyMoney"));if(amount<=0){result.skipped++;continue}const occurredAt=date(get(r,"Date")),title=text(get(r,"Pand"))||"مصروف قديم";ops.push({updateOne:{filter:{legacyKey:lk},update:{$setOnInsert:{id:id("document",lk),legacyKey:lk,number:`LEG-EXP-${text(get(r,"id"))}`,kind:"expense",status:"posted",paymentMethod:accountMap.get(text(get(r,"BankID")))??null,title,total:amount,dueTotal:0,paidTotal:amount,occurredAt,lines:[{id:id("line",lk),productId:null,description:title,quantity:1,unitPrice:amount,lineTotal:amount}]}},upsert:true}})}result.processed=read("safeTB").length;result.created=ops.length;result.mongoRoundTrips+=await bulk(db.collection("documents"),ops);return result;}
  if(phase==="finalize"){await rebuildCounters(db);result.mongoRoundTrips++;return result}return result;
 } finally {sqlite.close()}
}

/** Compatibility helper for callers/tests; intentionally has no encompassing transaction. */
export async function executeLegacyImport(db:Db, _session:unknown, bytes:Uint8Array, stockPolicy:"current"|"imported"="current") { const phases:Record<string,LegacyPhaseResult>={};for(const phase of LEGACY_IMPORT_PHASES)phases[phase]=await executeLegacyImportPhase(db,bytes,phase,stockPolicy);return phases; }
