import { randomUUID } from "node:crypto";
import type { SqliteDatabase as Db } from "../lib/sqlite.ts";
import { buildDataAccImportPackage, executeLegacyImportPhase, inspectLegacyDatabase, LEGACY_IMPORT_PHASES, type LegacyImportPhase } from "./dataacc-sqlite.ts";
import { finishLegacyUpload, removeLegacyUpload } from "./upload-store.ts";
import { createNativeBackup, stringifyBackup } from "../lib/backup.ts";
import { buildImportPreview } from "../migration/preview.ts";
import type { AccountBalancePolicy, StockPolicy } from "../migration/types.ts";

const labels:Record<LegacyImportPhase,string>={warehouses:"المخازن",parties:"العملاء والموردين",accounts:"الحسابات",products:"المنتجات",stocks:"أرصدة المخزون",sales:"فواتير البيع",purchases:"فواتير الشراء",expenses:"المصاريف",finalize:"إنهاء الاستيراد"};
const countKeys:Record<LegacyImportPhase,string>={warehouses:"warehouses",parties:"parties",accounts:"accounts",products:"products",stocks:"stocks",sales:"sales",purchases:"purchases",expenses:"expenses",finalize:"finalize"};
const publicFailure="تعذر إكمال الاستيراد. يمكنك إعادة المحاولة باستخدام رقم عملية الاستيراد.";
export async function createImportSafetyBackup(db:Db,importRunId:string,createdAt=new Date()){const backup=await createNativeBackup(db),backupId=randomUUID();await db.collection("importSafetyBackups").insertOne({id:backupId,importRunId,createdAt,expiresAt:new Date(createdAt.getTime()+30*86400000),backup:stringifyBackup(backup)});return backupId}
export async function createLegacyImportRun(db:Db,uploadId:string,stockPolicy:StockPolicy="keep-current",accountBalancePolicy:AccountBalancePolicy="keep-current",filename?:string){
 const startedAt=new Date(),id=randomUUID(),bytes=await finishLegacyUpload(uploadId),legacyPreview=await inspectLegacyDatabase(bytes),pkg=await buildDataAccImportPackage(bytes,filename),preview=await buildImportPreview(db,pkg),totals=Object.fromEntries(legacyPreview.groups.filter(x=>x.status==="ready").map(x=>[x.key,x.count]));
 let backupId:string;try{backupId=await createImportSafetyBackup(db,id,startedAt)}catch(error){console.error(JSON.stringify({event:"import_safety_backup_failed",importRunId:id,error:error instanceof Error?error.message:String(error)}));throw new Error("تعذر إنشاء نسخة أمان قبل الاستيراد.")}
 const run={id,sourceType:"dataacc-sqlite",source:{type:"dataacc-sqlite",filename:filename||"dataacc.sqlite",fingerprint:pkg.source.fingerprint},filename:filename||"dataacc.sqlite",fingerprint:pkg.source.fingerprint,uploadId,stockPolicy,accountBalancePolicy,state:"created",phase:"parse",phaseIndex:0,progress:{processed:0,total:0,label:"فحص الملف"},counts:{},totals,reviewCount:preview.groups.reduce((n,x)=>n+x.review,0)+pkg.unknownGroups.reduce((n,x)=>n+x.count,0),previewSummary:preview.groups.map(({key,count,created,matched,review,skipped,unsupported})=>({key,count,created,matched,review,skipped,unsupported})),unknownGroups:pkg.unknownGroups,backupIdBeforeImport:backupId,startedAt,createdAt:startedAt,updatedAt:startedAt,expiresAt:new Date(Date.now()+24*60*60*1000)};
 await db.collection("importRuns").insertOne(run);console.info(JSON.stringify({event:"import_started",importRunId:id,sourceType:"dataacc-sqlite",phase:"parse",startedAt}));return publicRun(run);
}
const publicRun=(run:Record<string,unknown>)=>({importRunId:run.id,sourceType:run.sourceType,filename:run.filename,fingerprint:run.fingerprint,state:run.state,phase:run.phase,progress:run.progress,counts:run.counts,reviewCount:run.reviewCount,previewSummary:run.previewSummary,unknownGroups:run.unknownGroups,backupIdBeforeImport:run.backupIdBeforeImport,startedAt:run.startedAt,completedAt:run.completedAt,updatedAt:run.updatedAt,publicError:run.publicError});
export async function getLegacyImportRun(db:Db,id:string){
 const run=await db.collection("importRuns").findOne({id})??await db.collection("legacyImportRuns").findOne({id});
 if(!run)throw Object.assign(new Error("عملية الاستيراد غير موجودة أو انتهت صلاحيتها"),{status:404});
 return publicRun(run);
}
export async function advanceLegacyImportRun(db:Db,id:string){
 const collection=db.collection("importRuns"),run=await collection.findOne({id})??await db.collection("legacyImportRuns").findOne({id});if(!run)throw Object.assign(new Error("عملية الاستيراد غير موجودة أو انتهت صلاحيتها"),{status:404});if(run.state==="completed")return publicRun(run);
 const phase=LEGACY_IMPORT_PHASES[Number(run.phaseIndex)] as LegacyImportPhase|undefined;if(!phase)return publicRun(run);const phaseStarted=Date.now(),total=Number(run.totals?.[countKeys[phase]]??0);
 await collection.updateOne({id},{$set:{state:phase,phase,progress:{processed:0,total,label:labels[phase]},updatedAt:new Date()}});
 try {const bytes=await finishLegacyUpload(String(run.uploadId)),result=await executeLegacyImportPhase(db,bytes,phase,run.stockPolicy==="use-imported"?"imported":"current",run.accountBalancePolicy as AccountBalancePolicy);if(["warehouses","parties","accounts","products"].includes(phase)){const pkg=await buildDataAccImportPackage(bytes,String(run.filename??"")),matched=await buildImportPreview(db,pkg),key=phase==="accounts"?"paymentAccounts":phase,group=matched.groups.find(x=>x.key===key);if(group){const operations=group.matches.filter(x=>x.matchType==="exact"&&x.targetId).map(x=>({updateOne:{filter:{sourceType:"dataacc-sqlite",sourceEntityType:key,sourceKey:x.sourceKey},update:{$set:{importRunId:id,targetEntityType:key,targetId:x.targetId,matchType:x.matchType,matchReason:x.reason,updatedAt:new Date()},$setOnInsert:{createdAt:new Date()}},upsert:true}}));if(operations.length)await db.collection("importMappings").bulkWrite(operations)}}const nextIndex=Number(run.phaseIndex)+1,completed=nextIndex>=LEGACY_IMPORT_PHASES.length,updatedAt=new Date();await collection.updateOne({id},{$set:{state:completed?"completed":LEGACY_IMPORT_PHASES[nextIndex],phase:completed?"finalize":LEGACY_IMPORT_PHASES[nextIndex],phaseIndex:nextIndex,progress:{processed:result.processed,total:total||result.processed,label:labels[phase]},[`counts.${phase}`]:result,updatedAt,completedAt:completed?updatedAt:null},$unset:{publicError:"",error:""}});console.info(JSON.stringify({event:"import_phase_completed",importRunId:id,phase,processed:result.processed,elapsedMs:Date.now()-phaseStarted,mongoRoundTrips:result.mongoRoundTrips}));if(completed)await removeLegacyUpload(String(run.uploadId));return publicRun((await collection.findOne({id}))!)}catch(error){const e=error as Error&{code?:unknown;errorLabels?:unknown};console.error(JSON.stringify({event:"import_failed",importRunId:id,phase,processed:0,elapsedMs:Date.now()-phaseStarted,error:{name:e.name,message:e.message,code:e.code,errorLabels:e.errorLabels,stack:e.stack}}));await collection.updateOne({id},{$set:{state:"failed",phase,publicError:`${publicFailure} رقم العملية: ${id}`,error:{name:e.name,code:e.code,message:e.message},updatedAt:new Date()}});return publicRun((await collection.findOne({id}))!)}
}

export async function listImportRuns(db:Db){return (await db.collection("importRuns").find({}).sort({createdAt:-1}).limit(20).toArray()).map(publicRun)}
